### ISSUE TITLE
Add verify_ssl option

### ISSUE THREAD

**Issue by Kistelini** [mautrix/whatsapp#10]
My homeserver only has a self-signed certificate which leads to this error:

`[Sep 25, 2018 15:23:06] [WARN] Failed to update bot avatar: Post https://$homeserver:8448/_matrix/client/r0/register?access_token=t2amBrOienrTRDciHgs3J1AbG3hdSTBRGLmoKwPh51mlPSMm4GQZeJOwQ2PAgt0c&user_id=%40whatsappbot%3A$homeserver: x509: certificate signed by unknown authority`

**Comment by tulir** [comment]
This isn't important at all since servers need real certs now and local servers can use non-TLS connections.
