### ISSUE TITLE
Some received messages are not bridged

### ISSUE THREAD

**Issue by julianuu** [mautrix/whatsapp#113]
Once in a while, a message I receive in whatsapp doesn't show up in matrix. I don't see anything suspicious in the logs of the bridge. It looks like the message just doesn't exist, even though I see it in whatsapp. It happens to maybe one message in 300, or once every few weeks. I also don't see a pattern. It can effect a few messages in a row that are being sent within a few minutes. And so far only in chat, but that might be a coincidence because by far most of my whatsapp messages belong to this chat.

Not sure how helpful this description is, but I just don't know how to narrow down the problem.

**Comment by rreuvekamp** [comment]
I'm experiencing this as well.

For instance, I received two messages from someone. I initially only received the second on Matrix.

Screenshot in RiotX: https://remi.im/tmp/wa-bug1.png

Screenshot in WA: https://remi.im/tmp/wa-bug2.png

The logs don't indicate anything special. The second message in logged (the the line in which the second message is received is bold). There is no trace of the first.

> [Feb 17, 2020 10:35:46] [Command handler/DEBUG] @remi:remi.im sent 'reconnect' in !mZLbsdQIrhbsRvaGKW:remi.im
> [Feb 17, 2020 10:35:46] [User/@remi:remi.im/WARN] Error while reconnecting: already logged in
> [Feb 17, 2020 10:35:46] [User/@remi:remi.im/DEBUG] Disconnecting due to failed session restore in reconnect command...
> [Feb 17, 2020 13:14:48] [Command handler/DEBUG] @remi:remi.im sent 'reconnect' in !mZLbsdQIrhbsRvaGKW:remi.im
> [Feb 17, 2020 13:14:49] [User/@remi:remi.im/ERROR] WhatsApp error: error processing data: error decoding binary: could not decode binary: invalid string with tag 174
> [Feb 17, 2020 13:14:49] [User/@remi:remi.im/DEBUG] JSON message: ["Blocklist",{"id":1,"blocklist":[]}]
> [Feb 17, 2020 13:14:49] [User/@remi:remi.im/DEBUG] JSON message: ["Stream","update",true,"0.4.613"]
> [Feb 17, 2020 13:14:49] [User/@remi:remi.im/DEBUG] JSON message: ["Props",{"webVoipInternalTester":false,"webCleanIncomingFilename":1,"webEnableModelStorage":false,"wsCanCacheRequests":false,"fbCrashlog":true,"bucket":"","gifSearch":"tenor","SPAM":true,"SET_BLOCK":true,"MESSAGE_INFO":true,"maxFileSize":100,"media":64,"maxSubject":25,"maxParticipants":257,"videoMaxEdge":960,"imageMaxKBytes":1024,"edit":1,"imageMaxEdge":1600,"frequentlyForwardedMessages":1,"suspiciousLinks":1,"fwdUiStartTs":📞,"restr
> ictGroups":1,"multicastLimitGlobal":5,"finalLiveLocation":1,"frequentlyForwardedMax":5,"mmsMediaKeyTTL":172800,"stickers":1,"announceGroups":1001,"groupDescLength":512}]
> [Feb 17, 2020 13:14:49] [User/@remi:remi.im/INFO] Chat list received
> [Feb 17, 2020 13:14:49] [User/@remi:remi.im/DEBUG] Locking processing of incoming messages and starting post-login sync
> [Feb 17, 2020 13:14:49] [User/@remi:remi.im/INFO] Reading chat list
> [Feb 17, 2020 13:14:49] [User/@remi:remi.im/DEBUG] Creating personal filtering community whatsapp_remi=remi.im
> [Feb 17, 2020 13:14:49] [User/@remi:remi.im/DEBUG] Personal filtering community  already existed
> [Feb 17, 2020 13:14:49] [User/@remi:remi.im/DEBUG] Chat list receive confirmation received in PostLogin
> [Feb 17, 2020 13:14:49] [User/@remi:remi.im/DEBUG] Post-login portal sync complete, unlocking processing of incoming messages.
> [Feb 17, 2020 13:14:49] [User/@remi:remi.im/WARN] Failed to add !rNGAqENKNlhQTqNPey:remi.im to +whatsapp_remi=remi.im:remi.im: msg=Failed to PUT JSON to /_matrix/client/r0/groups/+whatsapp_remi=remi.im:remi.im/admin/rooms/!rNGAqENKNlhQTqNPey:remi.im code=500 wrapped=M_UNKNOWN: Internal server error
> [Feb 17, 2020 13:14:49] [User/@remi:remi.im/WARN] Failed to invite @whatsapp_📞:remi.im to +whatsapp_remi=remi.im:remi.im: msg=Failed to PUT JSON to /_matrix/client/r0/groups/+whatsapp_remi=remi.im:remi.im/admin/users/invite/@whatsapp_📞:remi.im code=400 wrapped=M_UNKNOWN: User already in group
> [Feb 17, 2020 13:14:49] [Matrix/@whatsapp_📞:remi.im/DEBUG] PUT https://remi.im/_matrix/client/r0/rooms/%21sZIGxNngHZLgRiBuUy:remi.im/send/m.room.message/go📞?ts=📞&user_id=%40whatsapp_📞%3Aremi.im {"msgtype":"m.text","body":"Ik ben erbij en eet mee 👍"}
> **[Feb 17, 2020 13:14:49] [Matrix/@whatsapp_📞:remi.im/DEBUG] PUT https://remi.im/_matrix/client/r0/rooms/%21PbanDFXtJsIGoMEnsg:remi.im/send/m.room.message/go📞?ts=📞&user_id=%40whatsapp_📞%3Aremi.im {"msgtype":"m.text","body":"Of koken, mag natuurlijk ook 🙊"}**
> [Feb 17, 2020 13:14:49] [Matrix/@whatsapp_📞:remi.im/DEBUG] PUT https://remi.im/_matrix/client/r0/rooms/%21FWBQnbwGbbcqtLItKv:remi.im/send/m.room.message/go📞?ts=📞&user_id=%40whatsapp_📞%3Aremi.im {"msgtype":"m.text","body":"Ik zat in de trein een boek te lezen. Iemand tegenover me: wojooow, jij leest een groot boek"}
> [Feb 17, 2020 13:14:49] [Matrix/@whatsapp_📞:remi.im/DEBUG] PUT https://remi.im/_matrix/client/r0/rooms/%21ygiNFNeMLIXtNuvhTo:remi.im/send/m.room.message/go📞?ts=📞&user_id=%40whatsapp_📞%3Aremi.im {"msgtype":"m.text","body":"Ik laat verstek gaan jongens.. Ik vind 't te moeilijk inschatten of ik in juni een weekend weg kan, en wil niet nadat 't geboekt is nog afzeggen.","format":"org.matrix.custom.html","formatted_body":"Ik laat verstek gaan jongens.. Ik vind \u0026#39;t te moeilijk inschatten of ik in juni een weekend weg kan, en wil niet nadat \u0026#39;t geboekt is nog afzeggen."}
> [Feb 17, 2020 13:14:49] [User/@remi:remi.im/WARN] Failed to add !cMAPSoEIAcShjwESCc:remi.im to +whatsapp_remi=remi.im:remi.im: msg=Failed to PUT JSON to /_matrix/client/r0/groups/+whatsapp_remi=remi.im:remi.im/admin/rooms/!cMAPSoEIAcShjwESCc:remi.im code=500 wrapped=M_UNKNOWN: Internal server error
> [Feb 17, 2020 13:14:49] [User/@remi:remi.im/WARN] Failed to add !wUqfFQMsGQWnDmGPAh:remi.im to +whatsapp_remi=remi.im:remi.im: msg=Failed to PUT JSON to /_matrix/client/r0/groups/+whatsapp_remi=remi.im:remi.im/admin/rooms/!wUqfFQMsGQWnDmGPAh:remi.im code=500 wrapped=M_UNKNOWN: Internal server error
> [Feb 17, 2020 13:14:49] [User/@remi:remi.im/WARN] Failed to add !LejWsKCRzJrzEGBEre:remi.im to +whatsapp_remi=remi.im:remi.im: msg=Failed to PUT JSON to /_matrix/client/r0/groups/+whatsapp_remi=remi.im:remi.im/admin/rooms/!LejWsKCRzJrzEGBEre:remi.im code=500 wrapped=M_UNKNOWN: Internal server error
> [Feb 17, 2020 13:14:49] [Portal/📞-📞@g.us/DEBUG] Handled message 187D2CBC616EEDC8851963CE075ACBCD -> $SsGkAqegEwyX22srVVOQCkPrEd7IiNYHNnLZNXeoU_U
> [Feb 17, 2020 13:14:49] [Portal/📞-📞@g.us/DEBUG] Handled message 74CFD6031A9C0E45F8C8E📞 -> $xZ3OTEs4H8cwChTfDv_Bxe_GAlQrYUuVS9V9GBL2lAQ
> [Feb 17, 2020 13:14:49] [Portal/📞-📞@g.us/DEBUG] Handled message 3EB0A986260CF9492DD9 -> $jAeDO3D4HtO3QaXa0zGirDeB8GAEIz6kQgIY6NwrCW0
> [Feb 17, 2020 13:14:49] [User/@remi:remi.im/INFO] Syncing puppet info from contacts
> [Feb 17, 2020 13:14:49] [Portal/📞@s.whatsapp.net-📞@s.whatsapp.net/DEBUG] Handled message A99FF195391E2C95B9A7171F253CC542 -> $u576YQd4IJVT_uMEP8_IlTFajBNTdQ22fA71BbfPqoA
> [Feb 17, 2020 13:14:49] [User/@remi:remi.im/WARN] Failed to invite @whatsapp_📞:remi.im to +whatsapp_remi=remi.im:remi.im: msg=Failed to PUT JSON to /_matrix/client/r0/groups/+whatsapp_remi=remi.im:remi.im/admin/users/invite/@whatsapp_📞:remi.im code=400 wrapped=M_UNKNOWN: User already in group
> [Feb 17, 2020 13:14:49] [User/@remi:remi.im/WARN] Failed to add !GgivtzPEKtmwqFZMrf:remi.im to +whatsapp_remi=remi.im:remi.im: msg=Failed to PUT JSON to /_matrix/client/r0/groups/+whatsapp_remi=remi.im:remi.im/admin/rooms/!GgivtzPEKtmwqFZMrf:remi.im code=500 wrapped=M_UNKNOWN: Internal server error
> [Feb 17, 2020 13:14:49] [User/@remi:remi.im/WARN] Failed to invite @whatsapp_📞:remi.im to +whatsapp_remi=remi.im:remi.im: msg=Failed to PUT JSON to /_matrix/client/r0/groups/+whatsapp_remi=remi.im:remi.im/admin/users/invite/@whatsapp_📞:remi.im code=400 wrapped=M_UNKNOWN: User already in group
> [Feb 17, 2020 13:14:49] [User/@remi:remi.im/WARN] Failed to add !BnfugmpDQGkOWslcas:remi.im to +whatsapp_remi=remi.im:remi.im: msg=Failed to PUT JSON to /_matrix/client/r0/groups/+whatsapp_remi=remi.im:remi.im/admin/rooms/!BnfugmpDQGkOWslcas:remi.im code=500 wrapped=M_UNKNOWN: Internal server error
> [Feb 17, 2020 13:14:49] [User/@remi:remi.im/WARN] Failed to invite @whatsapp_📞:remi.im to +whatsapp_remi=remi.im:remi.im: msg=Failed to PUT JSON to /_matrix/client/r0/groups/+whatsapp_remi=remi.im:remi.im/admin/users/invite/@whatsapp_📞:remi.im code=400 wrapped=M_UNKNOWN: User already in group
> [Feb 17, 2020 13:14:49] [User/@remi:remi.im/WARN] Failed to add !FUdOFMDwmIDVPISaxQ:remi.im to +whatsapp_remi=remi.im:remi.im: msg=Failed to PUT JSON to /_matrix/client/r0/groups/+whatsapp_remi=remi.im:remi.im/admin/rooms/!FUdOFMDwmIDVPISaxQ:remi.im code=500 wrapped=M_UNKNOWN: Internal server error
> [Feb 17, 2020 13:14:49] [User/@remi:remi.im/WARN] Failed to add !uMeUrBRvEabnEVDHNl:remi.im to +whatsapp_remi=remi.im:remi.im: msg=Failed to PUT JSON to /_matrix/client/r0/groups/+whatsapp_remi=remi.im:remi.im/admin/rooms/!uMeUrBRvEabnEVDHNl:remi.im code=500 wrapped=M_UNKNOWN: Internal server error
> [Feb 17, 2020 13:14:49] [User/@remi:remi.im/WARN] Failed to invite @whatsapp_📞:remi.im to +whatsapp_remi=remi.im:remi.im: msg=Failed to PUT JSON to /_matrix/client/r0/groups/+whatsapp_remi=remi.im:remi.im/admin/users/invite/@whatsapp_📞:remi.im code=400 wrapped=M_UNKNOWN: User already in group
> [Feb 17, 2020 13:14:49] [User/@remi:remi.im/WARN] Failed to add !acoXnwgonclOMmiGnx:remi.im to +whatsapp_remi=remi.im:remi.im: msg=Failed to PUT JSON to /_matrix/client/r0/groups/+whatsapp_remi=remi.im:remi.im/admin/rooms/!acoXnwgonclOMmiGnx:remi.im code=500 wrapped=M_UNKNOWN: Internal server error
> [Feb 17, 2020 13:14:49] [User/@remi:remi.im/WARN] Failed to add !VdGgqekLyQMcIjHOgN:remi.im to +whatsapp_remi=remi.im:remi.im: msg=Failed to PUT JSON to /_matrix/client/r0/groups/+whatsapp_remi=remi.im:remi.im/admin/rooms/!VdGgqekLyQMcIjHOgN:remi.im code=500 wrapped=M_UNKNOWN: Internal server error
> [Feb 17, 2020 13:14:49] [User/@remi:remi.im/WARN] Failed to add !JNROkGEiaMVsRIhfYC:remi.im to +whatsapp_remi=remi.im:remi.im: msg=Failed to PUT JSON to /_matrix/client/r0/groups/+whatsapp_remi=remi.im:remi.im/admin/rooms/!JNROkGEiaMVsRIhfYC:remi.im code=500 wrapped=M_UNKNOWN: Internal server error
> [Feb 17, 2020 13:14:49] [User/@remi:remi.im/WARN] Failed to invite @whatsapp_📞:remi.im to +whatsapp_remi=remi.im:remi.im: msg=Failed to PUT JSON to /_matrix/client/r0/groups/+whatsapp_remi=remi.im:remi.im/admin/users/invite/@whatsapp_📞:remi.im code=400 wrapped=M_UNKNOWN: User already in group
> [Feb 17, 2020 13:14:49] [User/@remi:remi.im/WARN] Failed to add !IMaThTVVwrndTHEYQn:remi.im to +whatsapp_remi=remi.im:remi.im: msg=Failed to PUT JSON to /_matrix/client/r0/groups/+whatsapp_remi=remi.im:remi.im/admin/rooms/!IMaThTVVwrndTHEYQn:remi.im code=500 wrapped=M_UNKNOWN: Internal server error
> [Feb 17, 2020 13:14:49] [User/@remi:remi.im/WARN] Failed to invite @whatsapp_📞:remi.im to +whatsapp_remi=remi.im:remi.im: msg=Failed to PUT JSON to /_matrix/client/r0/groups/+whatsapp_remi=remi.im:remi.im/admin/users/invite/@whatsapp_📞:remi.im code=400 wrapped=M_UNKNOWN: User already in group
> [Feb 17, 2020 13:14:49] [User/@remi:remi.im/WARN] Failed to add !bSrUuLovpZzXPTfsFq:remi.im to +whatsapp_remi=remi.im:remi.im: msg=Failed to PUT JSON to /_matrix/client/r0/groups/+whatsapp_remi=remi.im:remi.im/admin/rooms/!bSrUuLovpZzXPTfsFq:remi.im code=500 wrapped=M_UNKNOWN: Internal server error
> [Feb 17, 2020 13:14:49] [User/@remi:remi.im/WARN] Failed to invite @whatsapp_📞:remi.im to +whatsapp_remi=remi.im:remi.im: msg=Failed to PUT JSON to /_matrix/client/r0/groups/+whatsapp_remi=remi.im:remi.im/admin/users/invite/@whatsapp_📞:remi.im code=400 wrapped=M_UNKNOWN: User already in group
> [Feb 17, 2020 13:14:49] [User/@remi:remi.im/WARN] Failed to add !TDcQSDcINKbHbBQNIj:remi.im to +whatsapp_remi=remi.im:remi.im: msg=Failed to PUT JSON to /_matrix/client/r0/groups/+whatsapp_remi=remi.im:remi.im/admin/rooms/!TDcQSDcINKbHbBQNIj:remi.im code=500 wrapped=M_UNKNOWN: Internal server error
> [Feb 17, 2020 13:14:49] [User/@remi:remi.im/WARN] Failed to invite @whatsapp_📞:remi.im to +whatsapp_remi=remi.im:remi.im: msg=Failed to PUT JSON to /_matrix/client/r0/groups/+whatsapp_remi=remi.im:remi.im/admin/users/invite/@whatsapp_📞:remi.im code=400 wrapped=M_UNKNOWN: User already in group
> [Feb 17, 2020 13:14:49] [User/@remi:remi.im/WARN] Failed to add !rbDSCRxaGjAxubKVsG:remi.im to +whatsapp_remi=remi.im:remi.im: msg=Failed to PUT JSON to /_matrix/client/r0/groups/+whatsapp_remi=remi.im:remi.im/admin/rooms/!rbDSCRxaGjAxubKVsG:remi.im code=500 wrapped=M_UNKNOWN: Internal server error
> [Feb 17, 2020 13:14:49] [User/@remi:remi.im/WARN] Failed to add !mBhUHxeayeDajLjiEP:remi.im to +whatsapp_remi=remi.im:remi.im: msg=Failed to PUT JSON to /_matrix/client/r0/groups/+whatsapp_remi=remi.im:remi.im/admin/rooms/!mBhUHxeayeDajLjiEP:remi.im code=500 wrapped=M_UNKNOWN: Internal server error
> [Feb 17, 2020 13:14:49] [User/@remi:remi.im/WARN] Failed to invite @whatsapp_📞:remi.im to +whatsapp_remi=remi.im:remi.im: msg=Failed to PUT JSON to /_matrix/client/r0/groups/+whatsapp_remi=remi.im:remi.im/admin/users/invite/@whatsapp_📞:remi.im code=400 wrapped=M_UNKNOWN: User already in group
> [Feb 17, 2020 13:14:49] [User/@remi:remi.im/WARN] Failed to add !PbanDFXtJsIGoMEnsg:remi.im to +whatsapp_remi=remi.im:remi.im: msg=Failed to PUT JSON to /_matrix/client/r0/groups/+whatsapp_remi=remi.im:remi.im/admin/rooms/!PbanDFXtJsIGoMEnsg:remi.im code=500 wrapped=M_UNKNOWN: Internal server error
> [Feb 17, 2020 13:14:49] [User/@remi:remi.im/WARN] Failed to invite @whatsapp_📞:remi.im to +whatsapp_remi=remi.im:remi.im: msg=Failed to PUT JSON to /_matrix/client/r0/groups/+whatsapp_remi=remi.im:remi.im/admin/users/invite/@whatsapp_📞:remi.im code=400 wrapped=M_BAD_STATE: User already invited to group
> [Feb 17, 2020 13:14:49] [User/@remi:remi.im/WARN] Failed to add !ygiNFNeMLIXtNuvhTo:remi.im to +whatsapp_remi=remi.im:remi.im: msg=Failed to PUT JSON to /_matrix/client/r0/groups/+whatsapp_remi=remi.im:remi.im/admin/rooms/!ygiNFNeMLIXtNuvhTo:remi.im code=500 wrapped=M_UNKNOWN: Internal server error
> [Feb 17, 2020 13:14:49] [User/@remi:remi.im/WARN] Failed to add !nLcHYmTAXdyBaDekUQ:remi.im to +whatsapp_remi=remi.im:remi.im: msg=Failed to PUT JSON to /_matrix/client/r0/groups/+whatsapp_remi=remi.im:remi.im/admin/rooms/!nLcHYmTAXdyBaDekUQ:remi.im code=500 wrapped=M_UNKNOWN: Internal server error
> [Feb 17, 2020 13:14:49] [User/@remi:remi.im/INFO] Read chat list, updating user-portal mapping
> [Feb 17, 2020 13:14:49] [User/@remi:remi.im/INFO] Syncing portals
> [Feb 17, 2020 13:14:49] [Portal/📞-📞@g.us/INFO] Syncing portal for @remi:remi.im
> [Feb 17, 2020 13:14:50] [Portal/📞-📞@g.us/DEBUG] Not backfilling: no new messages
> [Feb 17, 2020 13:14:50] [Portal/📞-📞@g.us/INFO] Syncing portal for @remi:remi.im
> [Feb 17, 2020 13:14:50] [Portal/📞-📞@g.us/DEBUG] Not backfilling: no new messages
> [Feb 17, 2020 13:14:50] [Portal/📞-📞@g.us/INFO] Syncing portal for @remi:remi.im
> [Feb 17, 2020 13:14:51] [Portal/📞-📞@g.us/DEBUG] Not backfilling: no new messages
> [Feb 17, 2020 13:14:51] [Portal/📞@s.whatsapp.net-📞@s.whatsapp.net/INFO] Syncing portal for @remi:remi.im
> [Feb 17, 2020 13:14:51] [Matrix/@whatsapp_📞:remi.im/DEBUG] POST https://remi.im/_matrix/client/r0/rooms/%21PbanDFXtJsIGoMEnsg:remi.im/invite?user_id=%40whatsapp_📞%3Aremi.im {"user_id":"@remi:remi.im"}
> [Feb 17, 2020 13:14:51] [Portal/📞@s.whatsapp.net-📞@s.whatsapp.net/DEBUG] Not backfilling: no new messages
> [Feb 17, 2020 13:14:51] [Portal/📞-📞@g.us/INFO] Syncing portal for @remi:remi.im
> [Feb 17, 2020 13:14:51] [Portal/📞-📞@g.us/DEBUG] Not backfilling: no new messages
> [Feb 17, 2020 13:14:51] [Portal/📞-📞@g.us/INFO] Syncing portal for @remi:remi.im
> [Feb 17, 2020 13:14:52] [Portal/📞-📞@g.us/DEBUG] Not backfilling: no new messages
> [Feb 17, 2020 13:14:52] [Portal/📞-📞@g.us/INFO] Syncing portal for @remi:remi.im
> [Feb 17, 2020 13:14:52] [Portal/📞-📞@g.us/DEBUG] Not backfilling: no new messages
> [Feb 17, 2020 13:14:52] [Portal/📞@s.whatsapp.net-📞@s.whatsapp.net/INFO] Syncing portal for @remi:remi.im
> [Feb 17, 2020 13:14:52] [Matrix/@whatsapp_📞:remi.im/DEBUG] POST https://remi.im/_matrix/client/r0/rooms/%21bSrUuLovpZzXPTfsFq:remi.im/invite?user_id=%40whatsapp_📞%3Aremi.im {"user_id":"@remi:remi.im"}
> [Feb 17, 2020 13:14:52] [Portal/📞@s.whatsapp.net-📞@s.whatsapp.net/DEBUG] Not backfilling: no new messages
> [Feb 17, 2020 13:14:52] [Portal/📞-📞@g.us/INFO] Syncing portal for @remi:remi.im
> [Feb 17, 2020 13:14:53] [Portal/📞-📞@g.us/DEBUG] Not backfilling: no new messages
> [Feb 17, 2020 13:14:53] [Portal/📞-📞@g.us/INFO] Syncing portal for @remi:remi.im
> [Feb 17, 2020 13:14:53] [Portal/📞-📞@g.us/DEBUG] Not backfilling: no new messages
> [Feb 17, 2020 13:14:53] [Portal/📞-📞@g.us/INFO] Syncing portal for @remi:remi.im
> [Feb 17, 2020 13:14:54] [Portal/📞-📞@g.us/DEBUG] Not backfilling: no new messages
> [Feb 17, 2020 13:14:54] [Portal/📞@s.whatsapp.net-📞@s.whatsapp.net/INFO] Syncing portal for @remi:remi.im
> [Feb 17, 2020 13:14:54] [Matrix/@whatsapp_📞:remi.im/DEBUG] POST https://remi.im/_matrix/client/r0/rooms/%21IMaThTVVwrndTHEYQn:remi.im/invite?user_id=%40whatsapp_📞%3Aremi.im {"user_id":"@remi:remi.im"}
> [Feb 17, 2020 13:14:54] [Portal/📞@s.whatsapp.net-📞@s.whatsapp.net/DEBUG] Not backfilling: no new messages
> [Feb 17, 2020 13:14:54] [Portal/📞@s.whatsapp.net-📞@s.whatsapp.net/INFO] Syncing portal for @remi:remi.im
> [Feb 17, 2020 13:14:54] [Matrix/@whatsapp_📞:remi.im/DEBUG] POST https://remi.im/_matrix/client/r0/rooms/%21mBhUHxeayeDajLjiEP:remi.im/invite?user_id=%40whatsapp_📞%3Aremi.im {"user_id":"@remi:remi.im"}
> [Feb 17, 2020 13:14:54] [Portal/📞@s.whatsapp.net-📞@s.whatsapp.net/DEBUG] Not backfilling: no new messages
> [Feb 17, 2020 13:14:54] [User/@remi:remi.im/INFO] Finished syncing portals
> [Feb 17, 2020 13:15:22] [Matrix/@whatsapp_📞:remi.im/DEBUG] PUT https://remi.im/_matrix/client/r0/presence/@whatsapp_📞:remi.im/status?user_id=%40whatsapp_📞%3Aremi.im {"presence":"offline"}
> [Feb 17, 2020 13:15:22] [User/@remi:remi.im/DEBUG] JSON message: ["Presence",{"id":"📞@c.us","type":"unavailable","deny":true}]
> [Feb 17, 2020 13:15:24] [Matrix/@whatsapp_📞:remi.im/DEBUG] PUT https://remi.im/_matrix/client/r0/profile/@whatsapp_📞:remi.im/displayname?user_id=%40whatsapp_📞%3Aremi.im {"displayname":"Eva (WA)"}
> [Feb 17, 2020 13:15:39] [Matrix/@whatsapp_📞:remi.im/DEBUG] PUT https://remi.im/_matrix/client/r0/profile/@whatsapp_📞:remi.im/displayname?user_id=%40whatsapp_📞%3Aremi.im {"displayname":"jasper (WA)"}
> [Feb 17, 2020 13:15:50] [User/@remi:remi.im/INFO] Finished syncing puppet info from contacts
> 

Odly enough, the missing message did get bridged later: https://remi.im/tmp/wa-bug3.png

If it matters, the messages were unread in WA (had 8 unread messages, including my own which I hadn't yet read on WA, only on Matrix). If was only after I saw the message I got on Matrix didn't make sense, that I checked WhatsApp.

I'm experiencing other situations in which messages don't get bridged. (Which is a real downer as makes it unreliable) I'll see if I can improve this bug report when I catch it again.

**Comment by rreuvekamp** [comment]
Found it again yesterday.
I had a few (around 10) messages which I would expect to get bridged from WhatsApp to Matrix. After "reconnect", only the last one got bridged. Still nothing in the logs except for the 1 message that got bridged correctly, along with messages from other WA chats.

Just like last time, the messaged got bridged later. (In this case, the next day)

It seems that (for me) this bug can be narrowed down to: Sometimes only the last message from a WhatsApp chat is bridged to Matrix.

@julianuu is that also what you're experiencing?

Also, I was in a really large WhatsApp group (like 1000something messages a day). I left it in the hope that it would fix this bug, but it does not. But luckily I got a good reason to leave that spamfest :p

**Comment by julianuu** [comment]
@rreuvekamp you are saying all your messages got bridged eventually? This didn't happen for me. Otherwise it does sound pretty similar. Like that only the last message of a bunch of messages got bridged.

Another thing is that for me it also disproportionately often effected responses to images I sent. I very very roughly got around 10 replies to images and 3 of them didn't get bridged. Something like that

**Comment by rreuvekamp** [comment]
> you are saying all your messages got bridged eventually? This didn't happen for me. 

Yes this does happen, but I'm not sure if it always happens or just sometimes.

**Comment by Nothing4You** [comment]
Just had this happen to me when I had 2 messages pending in a group chat. First one was with an image if that matters, second one had text. Only the last one got bridged.
Same error:
```
[Apr 21, 2020 07:36:22] [User/@nothing4you:national-security.agency/ERROR] WhatsApp error: error processing data: error decoding binary: could not decode binary: invalid string with tag 174
```
Restarting the bridge also bridged the missing message.

**Comment by iexos** [comment]
I have a cron job to restart the bridge every 6 hours to deal with this. Its much more reliable for me now, I cannot remember an instance where a missing message did not get bridged with a restart at some point
