### ISSUE TITLE
Failed to bridge media (photos)

### ISSUE THREAD

**Issue by surakin** [mautrix/whatsapp#115]
I've noticed photos fail to bridge sometimes, in the following cases:

When I use normal whatsapp mobile client to send a picture, in Riot Web it shows up as 'failed to bridge media'

When I use riot mobile to send a photo, other people can see in on their phones, but not on Whatsapp Web.

(Using master mautrix-whatsapp, synapse 1.6.0, riot/android 0.9.8, riot/web 1.5.4)

When a 'failed to bridge media' message shows, this comes up in the log
[Nov 27, 2019 11:15:51] [Portal/xxxxxxxxxxx@s.whatsapp.net-xxxxxxxxxxxxx@s.whatsapp.net/ERROR] Failed to download media for 61FD30F1BC6934DA851D6A687E8A71A1: no url present

Sending a photo from riot shows no error or warning messages in the bridge log.

Photos sent from Riot show with the original size (several MB), photos coming from WA are scaled down to a few kb.

**Comment by surakin** [comment]
And this is what whatsapp web users see ![image](https://user-images.githubusercontent.com/683652/69720904-f888ff00-1113-11ea-9b9f-3baf72cad877.png)

**Comment by tulir** [comment]
This probably doesn't apply anymore
