### ISSUE TITLE
not migrated nicknames fro new chats

### ISSUE THREAD

**Issue by progserega** [mautrix/whatsapp#13]
In chats user have no nicknames.

Steps to reproduce:
1. Whatsapp-mobile have chat with "user1" in history and some public rooms.
2. scan QR-code, link mautrix-bridge to whatsapp-account.
3. In matrix show invites for public rooms (from whatsapp) and invite for private-chat of "user1".
4. Nickname of "user1" success migrate to matrix.
5. After success init mautrix-whatsapp, "user2" type new message to my whatsapp account
6. In matrix I see "invite"
7. Accept invite and "user2" in matrix have no nickname
8. Also all users in public rooms have no its nicknames.

![matrix](https://user-images.githubusercontent.com/1297163/47056974-032f5000-d202-11e8-80a3-5621afe1e434.png)

![whatsapp](https://user-images.githubusercontent.com/1297163/47056739-4806b700-d201-11e8-940e-8b5f5395434c.png)

**Comment by PureTryOut** [comment]
This should be fixed by ebe256b0cf2bca8a3c24c8cbfac6c91e9129043d, could you verify?

**Comment by progserega** [comment]
No - this is not help.

I update with:
go get -u maunium.net/go/mautrix-whatsapp

restart service bridge, invite from new users - and situation not changed.
![wa1](https://user-images.githubusercontent.com/1297163/47501930-f5389980-d8a9-11e8-8ec9-f8d621a66f83.png)
![wa2](https://user-images.githubusercontent.com/1297163/47501931-f5d13000-d8a9-11e8-913d-a2e56b5d3212.png)

**Comment by charvp** [comment]
I'm seeing the same issue. I configured my bridge a week and a half ago and names were synced correctly then, but for new chats the names aren't synced.

**Comment by pwr22** [comment]
I also see this, I need to restart the bridge to sync them.

**Comment by charvp** [comment]
Restarting the bridge isn't enough for me. Profile pictures are loaded, but names never show up.

**Comment by tulir** [comment]
This is probably fixed
