### ISSUE TITLE
Files over 100M on matrix side doesn't show at all on WA

### ISSUE THREAD

**Issue by olmari** [mautrix/whatsapp#144]
By testing we figured that if there are file on matrix-room over 100M it will not propagate to WA side at all, not even error is thrown (as in users in WA doesn't know anything). As WA does have limit of 100M, bridge could either say something to let peoples know, or even better, provide an link to said file-url in HS with some description with it like "user XXX sent insanely large PDF of 500MB, get it here:"

**Comment by tulir** [comment]
These send an error to Matrix now
