### ISSUE TITLE
Uninstall Mautrix and delete added Room/Contacts?

### ISSUE THREAD

**Issue by rajil** [mautrix/whatsapp#164]
Hello,
Please can you point out what is the correct way to delete the rooms/contacts added by the Mautrix bridge. I send a logout message to the whatsappbot, and 'left' the roomms/group via riot-desktop. All the Whatsapp Rooms/Groups are now being shown in 'Historical'. However the Group contact icons are still being shown.

What is the right procedure to remove the content added by the bridge?

Thanks

**Comment by ericmigi** [comment]
You can send the command `delete-all-portals` in the whatsapp bridge bot room to delete all the rooms/groups created by the bridge.

**Comment by rajil** [comment]
Great. My intention is to only accept direct messages from Whatsapp and ignore all the group messages. Is it possible to do that?

**Comment by ericmigi** [comment]
you can mark the group messages as 'low priority' by right clicking them in Riot and also set notification to 'mute'

**Comment by rajil** [comment]
On initial sync/invite, I 'rejected' the group invites. The groups don't appear in Riot now. Hopefully, they won't appear when the bridge reconnects.
