### ISSUE TITLE
[Bug] Video doen't work since few commits

### ISSUE THREAD

**Issue by DoM1niC** [mautrix/whatsapp#216]
Video doen't work since few commits

`⚠ Your message may not have been bridged: message sending responded with 413`

**Comment by tulir** [comment]
That sounds like video is too big

**Comment by DoM1niC** [comment]
> That sounds like video is too big

Strange in the past I uploaded the same like this & this error wasn't any Problem, my 2nd Handy was converting the Video & all was finde... Video's around 10-30 sec not more...

**Comment by DoM1niC** [comment]
> > That sounds like video is too big
> 
> Strange in the past I uploaded the same like this & this error wasn't any Problem, my 2nd Handy was converting the Video & all was fine... Video's around 10-30 sec not more...
> 
> Nothing was changed like before it working fine here... :( since I updated the Source and now it's bricked... I reset to current Master without success

ok it seems you are right smaller Videos works, but it seems the Web WhatsApp Endpoint is now limited as before I sendet bigger vids without any problems :( 

Element e.g. Android Version need a simple Video converting Feature so far to solve this one here finally, Instagram Videos are are around 7-10 MB -> this works fine....

**Comment by topikuning** [comment]
i have tried 25M and works fine

**Comment by DoM1niC** [comment]
> i have tried 25M and works fine

I create often Videos with OpenCamera fully native in H264/AAC so far but will not working doen't matter which size in my Case, if you I publish e.g. on Instagram and download it & repost so it's works.
