### ISSUE TITLE
Prebuild executable does not work on Ubuntu 20.04

### ISSUE THREAD

**Issue by derritter88** [mautrix/whatsapp#221]
I downloaded the prebuild whatsapp bridge + all requirements to run it according to the wiki (additional compilation stuff as well).
Unfortunately the file does not start and throws the same error messages as mentioned here: [libolm.so.3 on Ubuntu 18.04](https://github.com/tulir/mautrix-whatsapp/issues/181#issuecomment-633354426)

Please note that I wanted to run the bridge with Ubuntu 20.04 where the libolm3 library is available.

When compiling the bridge it works without any issues.

**Comment by tulir** [comment]
Prebuilt executables haven't required libolm for some time now (they have it statically compiled), so this is probably fixed

**Comment by derritter88** [comment]
It works now - thanks!
