### ISSUE TITLE
All comments in config.yaml are wiped when generating registration.yaml

### ISSUE THREAD

**Issue by benwaffle** [mautrix/whatsapp#243]
1. run `docker run --rm -v $PWD:/data:z dock.mau.dev/tulir/mautrix-whatsapp:latest`
2. edit config.yaml
3. run `docker run --rm -v $PWD:/data:z dock.mau.dev/tulir/mautrix-whatsapp:latest`
4. config.yaml comments are gone

**Comment by tulir** [comment]
This is expected, Python is the only language where YAML comments can be easily preserved.

Go happens to be the only other language with a comment-preserving YAML parser, but I haven't figured out how to actually use the v3 go-yaml package for that.
