### ISSUE TITLE
Bridge stops working after a couple of days

### ISSUE THREAD

**Issue by ghost** [mautrix/whatsapp#247]
This has happened for the second time and I don't know what keeps happening. The bridge stops responding to my commands, people can see the messages that I have send but I do not receive messages being sent by them.

`] Unknown received message type: {Index:03709BDC4C958CB98F6D Jid:31646189582@c.us Owner:true Participant: Type:message}
`

**Comment by Gredin67** [comment]
same error message, but the bot responds to me. Messages are sent to WA but not received from WA.
I also see following errors in the logs
`Error backfilling history: server responded with status 404`
`Buffer is full, dropping message in`

**Comment by Gredin67** [comment]
After restarting the service, the lost/dropped messages get re-sync. Is there any bridge parameter to tweak to avoid dropping messages?

**Comment by chagai95** [comment]
Same problem happening to me. I just need to reconnect though I don't need to restart the bridge
