### ISSUE TITLE
Complete Initial Sync

### ISSUE THREAD

**Issue by Wunderharke** [mautrix/whatsapp#265]
Hello guys,

just wanted to ask if there is any way to do a complete sync (showing all groups and pm from whatsapp in matrix).
I've seen some configs like 'max age' and 'initial max chats' and I'm wondering if its save to just set them to IDK int_max or maybe -1?
If there any command for doing so (sync --create-all is not working) please give me a hint.

@tulir: Your mautrix bots are awesome, I really appreciate your work! They help me convince more people to use matrix while they are still using other massengers :)

**Comment by rreuvekamp** [comment]
Unfortunately I don't have the answer, but you might have more luck in the Matrix channel instead of the Issue tracker. 

#mautrix-whatsapp:maunium.net

**Comment by Wunderharke** [comment]
All right, I will try to inquire there.

For documentation purposes, I would like to share here what I have tested so far:

I have set `initial_chat_sync_count`, `initial_history_fill_count` and `sync_max_chat_age` to `9223372036854775807` (MAX_INT64) as well as `sync_direct_chat_list` set to `true`.
I have also increased the number of database connections and timeouts as well as buffers.

In a first attempt with sqlite the database was corrupted. In the meantime I use postgres for the bot.

When logging into whatsapp for the first time, _a lot_ of messages are now synced, this may take a few hours. My matrix server is very small, so I can not say how well it works when several users are to be synchronized simultaneously.

Still not all messages are synced, some direct messages are missing or whole conversations with individual persons are not synced.
Entering `sync --create-all` again shows that all chats have been synchronized. I could not see a pattern so far.

**Comment by buxel** [comment]
Thank you for documenting this here. I raised the same question some time ago on #mautrix-whatsapp:maunium.net . I think keeping track of this here makes sense.

**Comment by jahlives** [comment]
@Wunderharke 
I use(d) postgres as well, but had the issues like you describe. Changed back to sqlite and now much older messages are being synced. postgres was faster (claimed sync finished after 1hr) but it did not sync all the messages. Now with sqlite it takes waaaaay longer but I can see that messages from about 10 years ago are synced.  Is it possible that such "incomplete" syncs are related to the database backend used? Anyway for me it works much better with sqlite therefore I will stay with that

**Comment by Wunderharke** [comment]
This might indicate either a misconfiguration within postgres or some problem with how the box is handling backend entries.
I don't have any free time to test this at the moment. Using SQLite doesn't seem to be a valid option for large and frequently used instances, is it?

**Comment by jahlives** [comment]
@Wunderharke 
Think postgres or sqlite does not make a difference related to the completeness of sync. Started from scratch again (dropping all mautrix-whatsapp and synapse data) and chose postgres as backend for mautrix-whatsapp. Synced much more, some chats even completely (8 years back) BUT some chats (very active chats) not even for 2 years are complete. I cannot see a clear pattern in that behavior. It could be related to the amount of messages to be synced (I changed the values you describe as well)

**Comment by davralin** [comment]
I talked to @tulir on matrix, and this is his response to this issue:
> probably not going to either since https://github.com/matrix-org/matrix-doc/pull/2716 will happen soon and replace the current old message backfilling completely

So we should probably follow that issue. :-)

**Comment by tulir** [comment]
The history sync option now does as complete of a sync as possible (probably need to add options to limit that :thinking:)
