### ISSUE TITLE
Failed to connect to homeserver: failed to ensure registered 404 Not Found

### ISSUE THREAD

**Issue by SharkIng** [mautrix/whatsapp#269]
Got following error

```
[Feb  9, 2021 20:00:42] [ERROR] Failed to connect to homeserver: failed to ensure registered: failed to POST /_matrix/client/r0/register: 404 Not Found. Retrying in 10 seconds...
```

Running both `synapse` and `mautrix-whatsapp` on same host, both in docker.
- I am sure my homeserver setup is correct, I can use it
- I linked the `registration.yaml` file in my `homeserver.yml`
- I tested the `<homeserver.address domain>/_matrix/client/r0/register` and it works, returned following
```
{
  "errcode": "M_UNRECOGNIZED",
  "error": "Unrecognized request"
}
```
(I assume it's correct because when I try it through browser, it's GET request without any JSON passed in)

I also tested `curl <homeserver.address domain>/_matrix/client/r0/register` inside the plugins docker container, get same responded as above. So I don't think it is 404 Not Found

I thought i was wrong because the Synapse default setting disabled the user registration, so I enabled it by adding `enable_registration: true` in `homeserver.yaml`

Any other reason this doesn't work?

**Comment by pottah** [comment]
I have the same problem... Did you find a solution?

**Comment by sando1234** [comment]
Same Problem here. Any solution?

**Comment by pottah** [comment]
I wasn't able to get it to work with traefik as a reverse-proxy... But I found a workaround for my case. 
I just put the container in the same docker network as my synapse 😉

I think the way how the bridge is trying to connect to synapse through traefik isn't supported by the bridge. I guess with some configuring (traefik) it would be possible 😋

**Comment by sando1234** [comment]
I also found a fix, I simply changed the localhost value in the registration.yaml file to the IP of the Docker container. I hope I could help you with this error :D.

**Comment by jkuester** [comment]
Just wanted to record that I was in a similar situation to @pottah where I was running synapse and the bridge in separate docker containers behind Traefik and was running into this same issue. I was able to resolve the issue but putting synapse and the bridge into the same docker network and then configuring an alias address on that network for the bridge.  So, the relevant portions of my docker-compose look like this:

```.yml
services:
  synapse:
    image: matrixdotorg/synapse:v1.30.1
    volumes:
      - ./synapse/data:/data
      - ./whatsapp:/whatsapp
    networks:
      - traefik_external-net
  bridge_whatsapp:
    image: dock.mau.dev/mautrix/whatsapp:latest
    volumes:
      - ./whatsapp:/data:z
    networks:
      traefik_external-net:
        aliases:
          - whatsapp-bridge.example.com
```

Then in my bridge config.yaml file looks like:

```.yml
homeserver:
  # This is just using the Docker container name for the synapse container
  address: http://synapse:8008
...
appservice:
  address: http://whatsapp-bridge.example.com:29318
```

And my bridge registration.yaml file contains:

```.yml
url: http://whatsapp-bridge.example.com:29318
```

With this setup, everything seems to work.  I did try not using the network alias for the bridge and just referencing the docker container name (`bridge_whatsapp`) from the config.yaml/registration.yaml, but for some reason that did not work.  :shrug:

**Comment by tulir** [comment]
> referencing the docker container name (`bridge_whatsapp`)

That probably doesn't work because underscores aren't allowed in hostnames.

Anyway, looks like a setup issue, so closing this
