### ISSUE TITLE
m4a files acting very weird

### ISSUE THREAD

**Issue by chagai95** [mautrix/whatsapp#281]
They get shown as sent from WhatsApp but do not show on the other side.

They get sent fine on the official WhatsApp Web client and I did not find any m4a issues on these projects and I can not test to see if it would work with them to narrow down the issue...

https://github.com/Rhymen/go-whatsapp/search?q=m4a 
https://github.com/sigalor/whatsapp-web-reveng/search?q=m4a

**Comment by chagai95** [comment]
Also .enc

**Comment by DoM1niC** [comment]
for me all Audios formats does not work I tried Opus/AAC etc. without success
