### ISSUE TITLE
DNS lookup fails

### ISSUE THREAD

**Issue by Undearius** [mautrix/whatsapp#291]
After modifying config.yaml to point to my matrix server domain name and adding the registration file to synapse, running the docker results in this error
`[ERROR] Failed to connect to homeserver: failed to ensure registered: request error: Post "https://<my_domain>/_matrix/client/r0/register?user_id=%40whatsappbot%3A<my_domain>": dial tcp: lookup <my_domain> on [::1]:53: dial udp [::1]:53: connect: cannot assign requested address. Retrying in 10 seconds...  `

[::1]:53 is telling me it's trying to do a lookup for an IPv6 address when everything is configured with IPv4 addresses.

Is it possible that Golang defaults are kicking in with `defaultNS   = []string{"127.0.0.1:53", "[::1]:53"`
https://github.com/golang/go/blob/master/src/net/dnsconfig_unix.go

The container's /etc/resolv.conf file only has these two entries
`nameserver 1.1.1.1`
`nameserver 8.8.8.8`

**Comment by tulir** [comment]
This doesn't sound related to the bridge. There's nothing special related to DNS in the bridge nor in the docker image.

**Comment by Undearius** [comment]
Seems to be caused by this golang/go#25321

**Comment by Undearius** [comment]
May have been cause by this golang/go#45024

Either way, after updating the docker container, this is working now.
