### ISSUE TITLE
Cannot send images

### ISSUE THREAD

**Issue by mephlo** [mautrix/whatsapp#292]
I can't send images in whatsapp because i got the following error in my logs:
[Mar 26, 2021 20:24:40] [Portal/***@s.whatsapp.net-49***@s.whatsapp.net/ERROR] Failed to upload media in $***-to0HV5kQDGU: Post "https:///mms/imag
e/***=?auth=&token=***%3D": http: no Host in request URL

I don't know why there is no host in the post url...

**Comment by mephlo** [comment]
OK, seems like an issue in source libary:
https://github.com/Rhymen/go-whatsapp/issues/481

**Comment by MFAshby** [comment]
That issue in go-whatsapp seems closed. I can see the fork that mautrix-whatsapp is using has also been updated recently, so I tried building latest `master` of mautrix-whatsapp.

I'm still unable to send images via whatsapp, I get a different error in the logs though: 

> Error handling Matrix event $<long-number>: message sending responded with 400
