### ISSUE TITLE
DB migration is not working

### ISSUE THREAD

**Issue by alemairebe** [mautrix/whatsapp#304]
After some investivguation, I found the following : 
`bridge.MigrateDatabase()` call happens before `bridge.Init()`
https://github.com/tulir/mautrix-whatsapp/blob/v0.1.6/main.go#L400

Therefore, `bridge.Log` does not exist yet : https://github.com/tulir/mautrix-whatsapp/blob/v0.1.6/main.go#L215

However, `databse.New()`  at https://github.com/tulir/mautrix-whatsapp/blob/v0.1.6/main.go#L101 mentions `bridge.Log` which results to a null pointer exception as that entity is not created yet.

I guess an easy fix would be to move [log entity initialisation](https://github.com/tulir/mautrix-whatsapp/blob/v0.1.6/main.go#L215) to [NewBridge function](https://github.com/tulir/mautrix-whatsapp/blob/v0.1.6/main.go#L165)

**Comment by alemairebe** [comment]
I ran `pgloader mautrix-whatsapp.db postgres://redacted:redacted@redacted/redacted?sslmode=disable`
To try to migrate DB but than I get the following in WhatsApp bridge logs : 
```
Error processing data from websocket: error decoding binary: invalid hmac
encryptBinaryMessage(node) failed: encrypt failed: crypto/aes: invalid key size 121
```
Note : sqlite3 DB and postgres are both in UTF-8 encoding
When doing an new `login` from on the bridge , I have messages like : `[May 17, 2021 06:37:09] [Database/Message/WARN] Failed to decode message content: invalid character '#' looking for beginning of value`

**Comment by Kidswiss** [comment]
Can confirm running into both of these issues.
