### ISSUE TITLE
QR code not scanning

### ISSUE THREAD

**Issue by TRPB** [mautrix/whatsapp#307]
I'm guessing whatsapp changed something their end. on web.whatsapp.com the QR code now has a black and white whatsapp logo in the middle. 

I can register web.whatsapp.com but not the bridge bot no matter how long I hover over the QR code.

**Comment by frederictobiasc** [comment]
I just logged into 2 whatsapp accounts using the latest whatsapp apk and it still works fine for me.
Are you trying to set up whatsapp via the emulator or "native" on a smartphone?

**Comment by TRPB** [comment]
I'm using native Whatsapp. I'm not sure why but downloading the image and opening it in a different application worked. No matter how long I left it, I couldn't scan the code from element.

**Comment by frederictobiasc** [comment]
I never tried scanning the QR code in the element chat directly. But if this is an issue, it's related to element's creation/rendering of thumbnails.
Maybe for better usability, the bridge could add a text hint, stating to enlarge the QR code before scanning? Do you have another proposition?

**Comment by GIHAAAAAAAAAAAAAAAAAAAAAAAA** [comment]
i have the same issue..the first scan works fine..but the second scan doesn't work
