### ISSUE TITLE
WhatsApp error: websocket keepalive failed

### ISSUE THREAD

**Issue by MarkoBL** [mautrix/whatsapp#315]
Hi,

yesterday I updated to the latest version and I noticed some "slient" disconnects. The bot does not output any error, but when I send a `ping` I get a `Connection not OK: not connected`, therefore I have to manually reconnect using the `connect` command.

By reading the log, it seems that the connection is permanently closed after the fifth failed websocket keep alive without any notice. 

In the past, I already set `max_connection_attempts: 99999` as our local internet connection is sometimes not reliable and is gone for a few minutes and it takes up to 15 retries to reconnect.

Would it be possible to try to reconnect after the keep alive fails instead of failing silently?

Best regards

Here's the log:
```
[Jun 17, 2021 05:26:31] [User/@xxx:xxx/Conn/ERROR] Websocket keepalive for 0xc0007a5950 failed (error #1): connection timed out
[Jun 17, 2021 05:26:51] [User/@xxx:xxx/Conn/ERROR] Websocket keepalive for 0xc0007a5950 failed (error #2): connection timed out
[Jun 17, 2021 05:27:11] [User/@xxx:xxx/Conn/ERROR] Websocket keepalive for 0xc0007a5950 failed (error #3): connection timed out
[Jun 17, 2021 05:27:21] [User/@xxx:xxx/DEBUG] Marking online
[Jun 17, 2021 05:27:31] [User/@xxx:xxx/Conn/ERROR] Websocket keepalive for 0xc0007a5950 failed (error #4): connection timed out
[Jun 17, 2021 05:27:51] [User/@xxx:xxx/Conn/ERROR] Websocket keepalive for 0xc0007a5950 failed (error #5): connection timed out
[Jun 17, 2021 05:27:51] [User/@xxx:xxx/ERROR] WhatsApp error: websocket keepalive failed
[Jun 17, 2021 05:27:51] [User/@xxx:xxx/Conn/DEBUG] Disconnecting websocket
[Jun 17, 2021 05:27:51] [User/@xxx:xxx/Conn/DEBUG] Websocket read pump exiting 0xc0007a5950
[Jun 17, 2021 05:28:21] [Puppet/xxx@s.whatsapp.net/DEBUG] Skipping sync processing: custom user not connected to whatsapp
```

**Comment by tulir** [comment]
Probably doesn't apply on v0.2.0
