### ISSUE TITLE
The bridge kick all users from a room on reboot

### ISSUE THREAD

**Issue by erdnaxeli** [mautrix/whatsapp#316]
Sometime when restarting the docker image after pulling the last one, the bridge decides to kick every body in a room, and to remove the topic and the room name. Usually it does that in one room only, and forcing a sync fix the room (the users join back), but it seems this time it does not fix it :(

I noticed this error in the logs:
> [Jun 17, 2021 07:59:12] [User/@erdnaxeli:cervoi.se/Conn/ERROR] WhatsApp JSON parse error: json: cannot unmarshal object into Go value of type whatsapp.JSONMessage
> [Jun 17, 2021 07:59:12] [User/@erdnaxeli:cervoi.se/DEBUG] JSON message with tag 1623916752.--3: {"status":404}

![wa](https://user-images.githubusercontent.com/479441/122354854-b0c60480-cf51-11eb-876f-c52163259aa3.png)

**Comment by erdnaxeli** [comment]
Ok, rebooting the bridge and forcing a sync again fixed the room :shrug:

**Comment by tulir** [comment]
Probably doesn't apply on v0.2.0
