### ISSUE TITLE
Nicer mapping of editing messages on the WhatsApp side

### ISSUE THREAD

**Issue by chagai95** [mautrix/whatsapp#319]
Instead of sending the whole message with a * at the beginning, the edited message could be compared with the original message and only the part that was edited could be sent with the * at the beginning.

This could get complicated but I will try noticing some common use cases and maybe if the difference is too big it could just fall back to the what is implemented now (sending the whole message again)

**Comment by tulir** [comment]
Any mapping of edits is not going to happen. I might accept a pull request to stop bridging edit events entirely, but other than that users are expected to know not to edit messages.

In the future there should be a way for bridges to inform clients which features are supported and clients will be able to hide unsupported features

**Comment by chagai95** [comment]
Ok thanks for answering, I think it's still important for rooms bridged to another platform (i.e. Telegram). Maybe this could be made configurable? Or even better have the clients let you choose what message should be shown on WhatsApp with I dialog of some sort?

**Comment by pagdot** [comment]
An alternative (and I guess easier) approach could be to delete the original message and send the edited one without the `*`

**Comment by chagai95** [comment]
I think you can't delete messages after a certain amount of time on WhatsApp... And I believe deleting messages is not yet implemented via relaybot
