### ISSUE TITLE
Encrypt messages in database

### ISSUE THREAD

**Issue by bilal-78699** [mautrix/whatsapp#320]
I see that the messages in database are in plaintext. To have full end to end encryption the messages should be encrypted in database. It would be very nice to have this feature.

**Comment by bilal-78699** [comment]
@tulir any thoughts on this?

**Comment by Nothing4You** [comment]
while encryption in database would technically be possible it would have nothing to do with E2EE.

whatsapp crypto is not compatible with matrix crypto, so the bridge has to know the messages in plain text.

the only benefit an encrypted db storage would bring is to prevent someone with db access but no access to the bridge config from reading messages.

**Comment by tulir** [comment]
Indeed, it's not related to e2ee, but it would be nice to not store content at all. Right now the content is stored because replies wouldn't work otherwise.

**Comment by bilal-78699** [comment]
Thank you for the response. Yes it would be nice if we don't store content at all or it should be encrypted in DB just like matrix server is storing.
