### ISSUE TITLE
Messages sent/received when server is offline are not bridged

### ISSUE THREAD

**Issue by sphaerophoria** [mautrix/whatsapp#324]
Steps to reproduce

* Shutdown server running synapse + mautrix-whatsapp
* Send/receive messages on whatsapp running on phone
* Power on server and restart synapse/mautrix-whatsapp services
* Send message through bridge

Messages between when the server were shut down and when the first message was sent through the bridge are never added into the chat. Sending 'sync' to the whatsapp bot does not help.

I see messages in the logs saying "Not handling .... message is older than last bridge message".

Is it possible to get these messages backfilled? I'm concerned that I will miss messages during server outages depending on the root cause.

**Comment by sphaerophoria** [comment]
More relevant testing

* Messages sent from whatsapp on my phone are not synced through the bridge
* Shutting down the bridge and restarting it only receives messages after the last message sent from my phone
* If no messages are sent through my phone while the bridge is down I seem to get the missing messages

Maybe this is by design, but it would be nice if there was some way to re-sync my chat's to make sure I don't lose history

**Comment by Notmarrco** [comment]
I have the exact same issue.
It also seems to me that when back-filling large rooms in first connection there can be some connection issue between bridge and homeserver (i'm using dendrite) and thus some new messages are missing.
I would love a way to ask for a sync/backfill "force" for older messages.

**Comment by tulir** [comment]
Missed messages should now be received and bridged automatically instead of relying on the backfill mechanism
