### ISSUE TITLE
Muted status broadcasts are still bridged

### ISSUE THREAD

**Issue by apetresc** [mautrix/whatsapp#328]
WhatsApp has a feature to mute a contact's status updates (we all know that one guy who posts his stupid real-estate ads every day or something). You can activate it in the mobile app by long-tapping on a status message from that person and selecting "Mute status updates". Then it won't appear in your status update feed anymore (although there is a section at the very bottom that shows muted users and you can click into them individually to still see them).

The problem is that mautrix-whatsapp seems to ignore this mute status entirely. I still see muted users' status updates in my "WhatsApp Status Broadcast" room alongside all the others.

I'm not sure if this is a bug, intended functionality, or simply impossible to reimplement because muting is done client-side and not exposed via the API. But I'm filing it here anyway it case it can be resolved.

**Comment by tulir** [comment]
Mute status doesn't seem to be synced, so merging this with #455
