### ISSUE TITLE
Keep the extracted directory name consistent.

### ISSUE THREAD

**Issue by L0ric0** [mautrix/whatsapp#333]
unpacking the release tar ball of all versions up to v0.1.7 resulted in a directory named `mautrix-whatsapp-${version}`. Version v0.1.8 changed this to `whatsapp-v0.1.8`. 

This change resulted in the buildscripts for the mautrix-whatsapp package for archlinux to fail. As it is at the moment not possible to change the directory to which the packaging tools extract the source tarballs I would like to request to keep the default name of the directory to which the tarball is extracted stable, so that the buildscripts will not have to be changed for each version.

**Comment by tulir** [comment]
Source archives are auto-generated by GitHub, so it was automatically changed for all releases, not only v0.1.8. I don't think there's any way to override the directory name.
