### ISSUE TITLE
No messages recieved from contacts bridged to matrix

### ISSUE THREAD

**Issue by iisharankov** [mautrix/whatsapp#342]
I set up Whatsapp bridge a week ago and for the first few days it work well. Now, I've noticed no messages sent to me from others (group chats or DMs) reach my matrix server, but every time i reply via element, the messages are sent to the chat instantly on Whatsapp. It's a one way issue, and I can't have a conversation with anyone because of it.  Seems similar in behaviour to issue #113, but it's all messages from all groups.

Reconnect does not work (the bridge bot does not complain at all through any of this). A logout and login worked and i was able to message a person and have their responses  bridge to matrix... for 5 minutes. And then they stopped bridging again. No issues in logs and no clear suggestion what may be causing this. If there was I'd send it here.

Any help would be greatly appreciated.

**Comment by tulir** [comment]
Whatever the issue was, probably doesn't apply on v0.2.0
