### ISSUE TITLE
Compiled file

### ISSUE THREAD

**Issue by Carlosbarros967** [mautrix/whatsapp#343]
hello tulir,
Having seen this new v0.1.8 update, I have difficulty compiling the file to upload to amd64 server. Is there something to make it easier?

**Comment by tulir** [comment]
Forgot to add binaries to the release (added now), but you can always find them on the CI: https://mau.dev/mautrix/whatsapp/-/pipelines?scope=tags&page=1

**Comment by Carlosbarros967** [comment]
Thank you very much
