### ISSUE TITLE
Voice Message not bridging to element on iOS 

### ISSUE THREAD

**Issue by ArneNostitz** [mautrix/whatsapp#344]
hi, and first and foremost thanks for this amazing tool. it's a joy ever day. 

only thing that is a bump in the road are voice messages on iOS. they are bridged fine over from iOS. and they also work fine on desktop Mac. but on iOS they become links to "audio" files ... and they are just "data" files 

![C4413C0C-363D-4820-9A76-F50759BBB099](https://user-images.githubusercontent.com/16592596/132172733-ebb421b0-dad6-4112-91ab-9aa1e3ef8ea9.jpeg)
![0719204F-F5DF-48B4-8065-1689181D196B](https://user-images.githubusercontent.com/16592596/132172739-bdc0a3c8-c1d6-4e6b-b5a1-5fb09204b1d0.jpeg)

I did post at the element iOS GitHub first, but they meant I should bring it to your attention as well  

all the best and thanks again

**Comment by ArneNostitz** [comment]
they mentioned some information about file conformity which maybe could be an issue. https://github.com/vector-im/element-ios/issues/4753#issuecomment-913389650

**Comment by tulir** [comment]
The bridge follows the current spec for sending audio messages (https://matrix.org/docs/spec/client_server/r0.6.1#m-audio), Element iOS doesn't support that for some reason (but does support a non-standard voice message format). If/when the new format is standardized, the bridge will switch to sending those.
