### ISSUE TITLE
WhatsApp group invite messages do not bridge to Matrix

### ISSUE THREAD

**Issue by HenkKalkwater** [mautrix/whatsapp#350]
In WhatsApp you can disallow people from adding you to groups if they're not in your contacts, the setting for this can be found in the privacy settings. Those people that are disallowed to add you to a group, will be asked to send a group invite to you instead. These group invites look like this:

![group-invite](https://user-images.githubusercontent.com/4262067/134667400-1cf59558-ef14-48b1-a629-41923e13167f.png)

These are not bridged to Matrix currently, you don't even get a warning that an unsupported message has been sent. Could you consider implementing these?

**Comment by tulir** [comment]
This was implemented some time ago
