### ISSUE TITLE
Messages from myself are not replicated by the bridge

### ISSUE THREAD

**Issue by blastrock** [mautrix/whatsapp#357]
Steps to reproduce:

1. Open whatsapp on your phone
2. Open a 1-to-1 conversation
3. Send a message

The message will not be replicated by mautrix-whatsapp. It does work for messages in group chats though.

When I do the above, I can see the following log:

```
mautrix-whatsapp     | [Oct 25, 2021 19:49:14] [User/@myself:myserver/DEBUG] JSON message with tag s8: ["Msg",{"cmd":"ack","id":"XXXXXXXXXXXXXXX","ack":1,"from":"MYNUMBER@c.us","to":"MYFRIENDNUMBER@c.us","t":1635191354}]
mautrix-whatsapp     | [Oct 25, 2021 19:49:14] [Portal/MYFRIENDNUMBER@s.whatsapp.net-MYNUMBER@s.whatsapp.net/DEBUG] Not handling XXXXXXXXXXXXXXX (text): sender is not known
mautrix-whatsapp     | [Oct 25, 2021 19:49:16] [User/@myself:myserver/DEBUG] JSON message with tag s10: ["Msg",{"cmd":"ack","id":"XXXXXXXXXXXXXXX","ack":2,"from":"MYNUMBER@c.us","to":"MYFRIENDNUMBER@c.us","t":1635191355}]
```

**Comment by blastrock** [comment]
Hi again,

I'm on mautrix-whatsapp v0.2.1+dev.79256096 (Nov 18 2021, 16:02:39) and the bug is still present. Should we reopen this? Am I the only one with this bug?

**Comment by tulir** [comment]
That error message doesn't exist anymore.

**Comment by blastrock** [comment]
Ok, I enabled debug logs again and saw it complain about double puppeting being disabled. I must have messed up somewhere. Anyway, I fixed the shared secret and it all works now.

Thank you for the quick answer!
