### ISSUE TITLE
Edit the error message sent from WhatsApp instead of deleting it

### ISSUE THREAD

**Issue by chagai95** [mautrix/whatsapp#361]
Sometimes I'm not sure if the deleted message is really from the person I'm speaking to or because some error was deleted. If you edit it to an empty message or maybe there is something better but at least then I want be bothered by the message

**Comment by tulir** [comment]
The bridge doesn't redact many error messages, so probably not worth doing

**Comment by chagai95** [comment]
When you don't have internet then it redacts all the error messages that got sent when you were offline...

**Comment by tulir** [comment]
Those error messages don't exist in v0.2.0
