### ISSUE TITLE
history not syncing in v20

### ISSUE THREAD

**Issue by RobDiek** [mautrix/whatsapp#370]
Greetings
I am using Matrix with Ansible/Docker. It automatically installed v020 - multidevice auth works however I dont get history to sync :( Is there any way to fix this?

**Comment by RobDiek** [comment]
This is my history config;

history_sync:
        create_portals: true
        max_age: 0
        backfill: true
        request_full_sync: true
        user_avatar_sync: true
        bridge_matrix_leave: true

**Comment by sumnerevans** [comment]
Do you have a server that supports infinite backfill via https://github.com/matrix-org/matrix-doc/pull/2716?
