### ISSUE TITLE
Failed to bridge media importing history [v0.2.0]

### ISSUE THREAD

**Issue by surakin** [mautrix/whatsapp#374]
Many rooms fail to import media with errors like this (I can see the media on the phone and whatsapp-web)
Failed to bridge media for A809DF4B4A2630921822BB9EB8365AC1: download failed with status code 404

**Comment by Notmarrco** [comment]
I have the same errors.
Since the media is downloaded and accessible, is there a way to force the bridge to reload the media or re-sync the message ?

@surakin what is your homeserver ? I personnally use dendrite. I'm under the impression that this error appears when the media is large, so that the event is send before fully downloading the media, which then cannot be bridged.

**Comment by surakin** [comment]
I use synapse. I haven't re-tested this yet lately.

**Comment by kruegermedia** [comment]
As of version v0.3.0 it is still occasionally an issue :)

**Comment by sumnerevans** [comment]
You can react with the :recycle: emoji on the message in order to tell your phone to re-upload the media and the bridge will update the corresponding message. I think there's some sort of bug in Element where the edits on backfilled messages sometimes don't show up correctly, but the edits do work.

**Comment by surakin** [comment]
> You can react with the recycle emoji on the message in order to tell your phone to re-upload the media and the bridge will update the corresponding message. I think there's some sort of bug in Element where the edits on backfilled messages sometimes don't show up correctly, but the edits do work.

This doesn't seem to do anything 🤔

**Comment by sumnerevans** [comment]
Like I said, it may not work in Element if they haven't fixed that bug. You should turn on hidden messages and see if a message edit came through for the message after you reacted to it.

**Comment by surakin** [comment]
> Like I said, it may not work in Element if they haven't fixed that bug. You should turn on hidden messages and see if a message edit came through for the message after you reacted to it.

oh, I was checking the bridge logs and I saw nothing

**Comment by kruegermedia** [comment]
> You can react with the ♻️ emoji on the message in order to tell your phone to re-upload the media and the bridge will update the corresponding message. I think there's some sort of bug in Element where the edits on backfilled messages sometimes don't show up correctly, but the edits do work.

Thanks a lot, it works for some media Files, even though it does not seem like an element issue as it is present on several clients.

Maybe it could be send periodically by the bridge itself, it is kind of tedious to do that for each file seperately 😊
