### ISSUE TITLE
Unable to login again after disconnecting

### ISSUE THREAD

**Issue by dubwoc** [mautrix/whatsapp#376]
I am not sure if this is what started the issue but I ended up having to move my phone number to a new phone. As such I had to invalidate the login via mautrix-whatsapp. That all seemed to work fine and then it started erroring randomly so I figured i'd try to relink it and now I am stuck in a perpetual situation where whenever I type login I get the following error:

>Unknown error while logging in: error decoding login resp ["Cmd",{"type":"update"}]: json: cannot unmarshal array into Go value of type map[string]interface {}
>Your WhatsApp connection was closed with websocket status code 1000. Use the reconnect command to reconnect.

In the console I am seeing something like:
> [User/@user:matrix.domain/ERROR] WhatsApp error: server closed connection,code: 1000,text:

This is using the latest image at dock.mau.dev/tulir/mautrix-whatsapp:latest ("Created": "2021-08-05T22:35:24.468384377Z",)

Let me know what else I can provide.

**Comment by tulir** [comment]
That means the bridge is outdated
