### ISSUE TITLE
Error in configuration at 'room_prejoin_state'

### ISSUE THREAD

**Issue by poltrian** [mautrix/whatsapp#381]
When i Restart Matrix
Error in configuration at 'room_prejoin_state':
Nov 09 08:51:29 matrix matrix-synapse[3728]:   ['/home/mautrix-whatsapp/registration.yaml'] is not of type 'object'

**Comment by jejo86** [comment]
Fresh install using compiled code from [mau.dev](https://mau.dev/mautrix/whatsapp/-/jobs/20106/artifacts/download?file_type=archive) and I have the exact same error.

@tulir How come you closed this issue? What is the solution?
