### ISSUE TITLE
    Failed to load config: yaml: line 31: could not find expected ':'

### ISSUE THREAD

**Issue by poltrian** [mautrix/whatsapp#382]
My configuration, line 31 is uri: mautrix-whatsapp.db

Database:
        # The database type. "sqlite3" and "postgres" are supported.
        type: postgres
        # The database URI.
        #   SQLite: File name is enough. https://github.com/mattn/go-sqlite3#connection-string
        #   Postgres: Connection string. For example, postgres://user:password@host/database?sslmode=disable
        postgres://user:xxxxxx@localhost/synapse_db?sslmode=disable
        uri: mautrix-whatsapp.db 
Whats means could not find expected ':'

**Comment by tulir** [comment]
That means there's a syntax error in your config, probably on the line above the one it mentions. Debugging config and other setup issues should be done in the Matrix room rather than GitHub issues (because they're issues with your setup rather than the bridge)
