### ISSUE TITLE
E2EE fails when a contact switches identity keys

### ISSUE THREAD

**Issue by BlackFloyd** [mautrix/whatsapp#384]
Since the switch to whatsmeow one of my contacts bought a new phone and consequently has a new identity key.
From the point where he switched phones I only got "Decrypting message from WhatsApp failed, waiting for sender to re-send" errors from him and he received the WhatsApp-equivalent ("Waiting for this message. This may take a while.") from me.

This went on for some days, so I had a look at the logs and saw this:

```
Error decrypting message from **phone number redacted**@s.whatsapp.net: failed to decrypt prekey message: Untrusted identity
```

Since I am a wreckless anarchist without any fear of consequences I made a backup and deleted his (presumingly) old identity key from the psql table:

```sql
DELETE FROM whatsmeow_identity_keys WHERE their_id LIKE '%**phone number redacted**%'; -- I know what I'm doing, trust me!
```

After restarting the bridge everything worked fine.

As for a solution to this... I know that this shouldn't "just work" because if we just ignored key changes this would kinda render E2EE useless, but imho there should be a method to accept new keys other than deleting the old one from the DB ;) Maybe WhatsApp's (opt-in) solution would be an idea here... If a new key is used, WA just displays a message that the key has changed and carries on with the new key.

Now I don't have any clue if this should be handled by mautrix-whatsapp or whatsmeow (or at all) but since handling this quietly in the background would basically diminish E2EE, I decided to post it here. Please let me know if I should re-post it in whatsmeow.

**Comment by scottwallacesh** [comment]
I too am seeing this and I am running the latest version (`May 21 2022, (22:20:29)`).  Do I need to update my DB as per OP, @tulir?
