### ISSUE TITLE
Audio messages not working on Android

### ISSUE THREAD

**Issue by Ulrar** [mautrix/whatsapp#398]
Hi,

I might be missing something but I have a whatsapp contact who loves sending audio messages, and they work fine in element web.
But on element Android they just shows as a download button labeled "audio", instead of the built-in audio player.

Is this expected, or am I missing some config ?
I know element's audio features are pretty new.

Thanks

**Comment by tulir** [comment]
It's a bug in Element Android, same as in Element iOS (#344)
