### ISSUE TITLE
Can I force mautrix to refetch every display name?

### ISSUE THREAD

**Issue by AdriDevelopsThings** [mautrix/whatsapp#401]
Hey,

I updated the display name template in the config file. Now I want that mautrix regenerate every display name with the new template. Is that possible?

Kind regards

**Comment by Nothing4You** [comment]
isn't that just `sync contacts`?

seems to do it for me at least

**Comment by AdriDevelopsThings** [comment]
> isn't that just `sync contacts`?
> 
> 
> 
> seems to do it for me at least

Yes, thanks, that works for me.
