### ISSUE TITLE
Login fails using multi-device API

### ISSUE THREAD

**Issue by pinnymz** [mautrix/whatsapp#422]
When upgrading from v0.1.8 to latest v0.2.3, I needed to log back in due to the revised WhatsApp multi-device API post v0.2.x.  Unfortunately, the QR login fails on the device (complains about checking device network connectivity) - running the latest WA version at this time.  Is there any way to turn off multi-device as an option?  Alternatively, any way to understand why the login is failing?

**Comment by pinnymz** [comment]
To clarify, when I try to login via the web app: opted-in to multi-device fails, opted-out works just fine.  I have no idea why, and the ansible deployment isn't letting me downgrade.  So stuck at the moment unless someone has any ideas around this.

**Comment by bjo81** [comment]
Did you try again?
```
Successfully logged in as +49xyz (device #14)
You were logged out from another device. Please link the bridge to your phone again.
```
According to the app, the login failed complaining about connectivity.

**Comment by bjo81** [comment]
Restarted the bridge, login worked again afterwards.

**Comment by pinnymz** [comment]
To be clear, what is entailed in restarting the bridge - just restart via systemd?

**Comment by bjo81** [comment]
> To be clear, what is entailed in restarting the bridge - just restart via systemd?

Yes.

**Comment by pinnymz** [comment]
I can now report that login worked on **the 25th try**.  Clearly the problem is with the Multidevice feature and not with the bridge itself.  But given that the feature is still in beta, and people are reporting being randomly logged out - can I petition for reintroducing the old login method until this issue is fixed?  At the moment (since v.0.2.x) multidevice is a hard requirement for the bridge, why does that need to be the case?

**Comment by tulir** [comment]
Supporting both methods would be too much effort, you can just start over with v0.1.9 if you don't want to use multidevice

**Comment by edwardcwang** [comment]
One thing to try: make sure your WhatsApp is up-to-date in your Android instance.
