### ISSUE TITLE
Error During Installation

### ISSUE THREAD

**Issue by Stomatic** [mautrix/whatsapp#425]
Hi,
I'm trying to install whatsapp bridge on my server, but I keep getting the same problem.
I tried several times but it doesn't work.
The server is only accessible in the local network, the dns are set to my pi-hole (the domain is matrix.elementmarchi.host).
Synapse server has been installed with docker and it's working.
My server is running Ubuntu 18.04

I get this when I try to install the bridge with _sudo docker run --restart unless-stopped -v `pwd`:/data:z dock.mau.dev/mautrix/whatsapp:latest_

_[Jan 21, 2022 21:57:53] [INFO] Initializing mautrix-whatsapp 0.2.3+dev.aacb1d57 (Jan 19 2022, 14:23:50)
[Jan 21, 2022 21:57:53] [DEBUG] Initializing database connection
[Jan 21, 2022 21:57:53] [DEBUG] Initializing state store
[Jan 21, 2022 21:57:53] [DEBUG] Initializing Matrix event processor
[Jan 21, 2022 21:57:53] [DEBUG] Initializing Matrix event handler
[Jan 21, 2022 21:57:53] [DEBUG] Bridge built with end-to-bridge encryption, but disabled in config
[Jan 21, 2022 21:57:53] [INFO] Bridge initialization complete, starting...
[Jan 21, 2022 21:57:53] [DEBUG] Running database upgrades
[Jan 21, 2022 21:57:53] [Database/Upgrade/INFO] Database currently on v0, latest: v35
[Jan 21, 2022 21:57:53] [Database/Upgrade/INFO] Upgrading database to v1: Initial schema
[Jan 21, 2022 21:57:53] [Database/Upgrade/INFO] Upgrading database to v3: Add timestamp column to messages
[Jan 21, 2022 21:57:53] [Database/Upgrade/INFO] Upgrading database to v4: Add last_connection column to users
[Jan 21, 2022 21:57:53] [Database/Upgrade/INFO] Upgrading database to v6: Add columns to store custom puppet info
[Jan 21, 2022 21:57:54] [Database/Upgrade/INFO] Upgrading database to v7: Add user-portal mapping table
[Jan 21, 2022 21:57:54] [Database/Upgrade/INFO] Upgrading database to v8: Add columns to store avatar MXC URIs
[Jan 21, 2022 21:57:54] [Database/Upgrade/INFO] Upgrading database to v9: Add columns to store portal in filtering community meta
[Jan 21, 2022 21:57:54] [Database/Upgrade/INFO] Upgrading database to v10: Move state store to main DB
[Jan 21, 2022 21:57:54] [Database/Upgrade/INFO] Upgrading database to v11: Add columns to store full member info in state store
[Jan 21, 2022 21:57:54] [Database/Upgrade/INFO] Upgrading database to v12: Adjust the length of column topic in portal
[Jan 21, 2022 21:57:54] [Database/Upgrade/INFO] Upgrading database to v13: Add encryption status to portal table
[Jan 21, 2022 21:57:55] [Database/Upgrade/INFO] Upgrading database to v14: Add crypto store to database
[Jan 21, 2022 21:57:55] [Database/Upgrade/INFO] Upgrading database to v15: Add outbound group sessions to database
[Jan 21, 2022 21:57:55] [Database/Upgrade/INFO] Upgrading database to v16: Add enable_presence column for puppets
[Jan 21, 2022 21:57:55] [Database/Upgrade/INFO] Upgrading database to v17: Add account_id to crypto store
[Jan 21, 2022 21:57:55] [Database/Upgrade/INFO] Upgrading database to v18: Add enable_receipts column for puppets
[Jan 21, 2022 21:57:55] [Database/Upgrade/INFO] Upgrading database to v19: Add megolm withheld data to crypto store
[Jan 21, 2022 21:57:55] [Database/Upgrade/INFO] Upgrading database to v20: Add cross-signing keys to crypto store
[Jan 21, 2022 21:57:56] [Database/Upgrade/INFO] Upgrading database to v21: Add sent column for messages
[Jan 21, 2022 21:57:56] [Database/Upgrade/INFO] Upgrading database to v22: Remove message content from local database
[Jan 21, 2022 21:57:56] [Database/Upgrade/INFO] Upgrading database to v23: Replace VARCHAR(255) with TEXT in the database
[Jan 21, 2022 21:57:56] [Database/Upgrade/INFO] Upgrading database to v24: Replace VARCHAR(255) with TEXT in the crypto database
[Jan 21, 2022 21:57:56] [Database/Upgrade/INFO] Upgrading database to v25: Add whatsmeow state store
[Jan 21, 2022 21:57:56] [Database/Upgrade/INFO] Upgrading database to v26: Update things for multidevice
[Jan 21, 2022 21:57:57] [Database/Upgrade/INFO] Upgrading database to v27: Add columns to store infinite backfill pointers for portals
[Jan 21, 2022 21:57:57] [Database/Upgrade/INFO] Upgrading database to v28: Add marker for WhatsApp decryption errors in message table
[Jan 21, 2022 21:57:57] [Database/Upgrade/INFO] Upgrading database to v29: Add relay user field to portal table
[Jan 21, 2022 21:57:57] [Database/Upgrade/INFO] Upgrading database to v30: Replace VARCHAR(255) with TEXT in the Matrix state store
[Jan 21, 2022 21:57:57] [Database/Upgrade/INFO] Upgrading database to v31: Store last read message timestamp in database
[Jan 21, 2022 21:57:57] [Database/Upgrade/INFO] Upgrading database to v32: Split last_used into last_encrypted and last_decrypted in crypto store
[Jan 21, 2022 21:57:57] [Database/Upgrade/INFO] Upgrading database to v33: Store source broadcast list in message table
[Jan 21, 2022 21:57:57] [Database/Upgrade/INFO] Upgrading database to v34: Add personal filtering space info to user tables
[Jan 21, 2022 21:57:58] [Database/Upgrade/INFO] Upgrading database to v35: Add support for disappearing messages
[Jan 21, 2022 21:57:58] [DEBUG] Checking connection to homeserver
[Jan 21, 2022 21:57:58] [Matrix/Bot/DEBUG] req #1: POST http://matrix.elementmarchi.host:8008/_matrix/client/r0/register?user_id=%40whatsappbot%3Aelementmarchi.host {"username":"whatsappbot","inhibit_login":true,"type":"m.login.application_service"}
**[Jan 21, 2022 21:57:58] [FATAL] The as_token was not accepted. Is the registration file installed in your homeserver correctly?**_

What am i doing wrong?

The registration file is:
_id: whatsapp
url: http://localhost:29318
as_token: bla bla bla
hs_token: bla bla bla
sender_localpart: bla bla bla
rate_limited: false
namespaces:
  users:
  - regex: ^@whatsapp_[0-9]+:elementmarchi.host$
    exclusive: true
  - regex: ^@whatsappbot:elementmarchi.host$
    exclusive: true_

And the path of the registration file is correctly pasted into homeserver.yaml file:
_app_service_config_files:
   -/home/user/mautrix-whatsapp/registration.yaml_

**Comment by AIndoria** [comment]
Having the exact same issue, except my url is pointed correctly towards my whatsapp instance as whatsapp:29318 (I can ping it via my homeserver docker console).

This issue **sometimes** resolves itself if you go and create a whatsappbot user yourself but eh...

**Comment by Stomatic** [comment]
Okay, but what password do I use?

**Comment by witchent** [comment]
Why was this closed? I have the same error: The as_token was not accepted. Is the registration file installed in your homeserver correctly?

Synapse starts and recognizes the appservice yaml, and in both the same as_token is used.
