### ISSUE TITLE
Getting error about InvalidCodepoint

### ISSUE THREAD

**Issue by IeuanK** [mautrix/whatsapp#426]
I set up the bot inside docker, bot itself says everything is fine, but it stays offline in Matrix and does not accept invites.  
Checked the Synapse log and it's showing this error:
`Error sending request to  PUT http://matrix_whatsapp:29318/transactions/1?access_token=<redacted>: InvalidCodepoint Codepoint U+005F at position 7 of 'matrix_whatsapp' not allowed`

I get this for all calls Synapse tries to send to the bridge.

Is this a known issue? How do I fix it?

**Comment by IeuanK** [comment]
Seems like it is saying that the underscore in matrix_whatsapp is not allowed?

**Comment by tulir** [comment]
That's correct, underscores aren't allowed in hostnames
