### ISSUE TITLE
Groups don't get Added to whatsapp space when invited

### ISSUE THREAD

**Issue by speatzle** [mautrix/whatsapp#428]
When using the `personal_filtering_spaces` config option:
Users that are added to a Group through Whatsapp don't have the new Room added to the Personal Filtering Space.
The User who creates the Group through Whatsapp properly get the room added to the Filtering Space.

Running the `sync space` command adds the Room to the Space correctly.

I had the Logs set to debug and there are no errors as far as i can see.

**Comment by HelderFSFerreira** [comment]
Hey,

I've talked with @speatzle and we narrowed it down to when at least 1 double pupeting enable.

AFAIK when double pupeting is enable only one room is created and it only adds the client processing room creation to the space.

**Comment by speatzle** [comment]
So as far as I understand it: if double puppeting is used by at least one user that has been added to the group then during the creation of the Room in https://github.com/mautrix/whatsapp/blob/9e39ce565b480b43cb1675c53e325239e41caae2/portal.go#L1147 addToSpace is only called for the user that is processing the room creation https://github.com/mautrix/whatsapp/blob/9e39ce565b480b43cb1675c53e325239e41caae2/portal.go#L1286

As a fix, we could just add a loop to iterate over all participants and call addToSpace for the other users.
Or we move the addToSpace calls down into SyncParticipants which is probably cleaner. But we would then have to check if the room is already in the users space since SyncParticipants is also called by UpdateMetadata.  https://github.com/mautrix/whatsapp/blob/9e39ce565b480b43cb1675c53e325239e41caae2/portal.go#L780 https://github.com/mautrix/whatsapp/blob/9e39ce565b480b43cb1675c53e325239e41caae2/portal.go#L926

Any opinions? I would be happy to make a PR to get this fixed

**Comment by speatzle** [comment]
@HelderFSFerreira, @tulir any opinions? I would like approval before i make a PR that won't get merged.

**Comment by natecovington** [comment]
This "WhatsApp Space" just showed up in my Element client after installing the latest update, I'm guessing this thread is discussing the same thing.  I'm not sure why because I'm not using the `personal_filtering_spaces` intentionally.  I didn't really like how the space just showed up by itself...

**Comment by speatzle** [comment]
@natecovington that appears to be a different issue

**Comment by natecovington** [comment]
Let me know if I should open a new thread... not a major deal to me because I just left the space. no harm no foul.

**Comment by ambroisie** [comment]
I am having an issue that looks similar to me: when enabling both `personal_filtering_spaces` and `encryption.allow` (as well as `encryption.default`), then creating a room with a single user results in it *not* being added to the WhatsApp space (even after running `sync space`).

To debug the issue, I tried running `sync space --create-portals`, which did not solve the issue, but *did* create rooms corresponding to my pre-existing *group* chats in the correct space.
