### ISSUE TITLE
[FeatureRequest] I want to post status messages in the WhatsApp status room

### ISSUE THREAD

**Issue by mikedolx** [mautrix/whatsapp#430]
Hi,

## What is the problem?

Currently when i post a message in the "WhatsApp Status Broadcast" room i get the notification 

`Your message was not bridged: sending to broadcast lists is not yet supported`

I understand this is a missing feature in the WhatsApp bridge. Correct me if I'm wrong!

## What is the desired output?
I would like to post messages in the "WhatsApp Status Broadcast" room and forward this messages to the device's WhatsApp status, so my contacts can see this status messages.

## Questions
- Is there any other way (workaround) to achieve the desired output?

As i couldn't find a feature request for this i am creating this one to track any discussion or possible progress in it.

**Comment by mikedolx** [comment]
Hi @tulir , is there another ticket that covers that feature request? Or will that feature request just not be implemented?

**Comment by sumnerevans** [comment]
I think Tulir implemented it.

See https://github.com/tulir/whatsmeow/commit/a05359d4385afd54d160b4152faeed298093f8dc and https://github.com/mautrix/whatsapp/commit/a4f57d175c046034af07723b1c27bc2e4b2c5be7#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4edR12

**Comment by mikedolx** [comment]
Amazing news! Thanks!
