### ISSUE TITLE
Failed to log in: unexpected connection event from server

### ISSUE THREAD

**Issue by cutec-chris** [mautrix/whatsapp#447]
since some days it seems not possible to use this bridge anymore

**Comment by tulir** [comment]
Your bridge is outdated

**Comment by cutec-chris** [comment]
Then docker dock.mau.dev/mautrix/whatsapp:latest is outdated ...

**Comment by cutec-chris** [comment]
with actual build from source, works thanks for the fast answer

**Comment by tulir** [comment]
The docker image gets built automatically so it's always up to date
