### ISSUE TITLE
Password in Log File

### ISSUE THREAD

**Issue by DanielSchuerhoff** [mautrix/whatsapp#465]
Hey all,

while configuring my Mautrix Whatsapp bride, I got an error:
(pulled from docker with docker logs)

 Failed to initialize database: failed to ensure database owner table exists: parse "postgres://mautrix-whatsapp:PASSWORDPASSWORDPASSWORD@postgres/mautrix-whatsapp?sslmode=disable": net/url: invalid userinfo

I think a password should definitely not be in any log file!
Or am I missing something here?

**Comment by tulir** [comment]
It only happens when the connection URL is invalid. Also, database passwords aren't that sensitive (the database shouldn't be exposed to the internet) and logs shouldn't be public anyway.
