### ISSUE TITLE
WhatsApp Reactions

### ISSUE THREAD

**Issue by thebiblelover7** [mautrix/whatsapp#489]
Reactions in WhatsApp were *just* released some days ago, but I just thought I'd drop by and see if you had plans of implementing it. 

Do you have any plans of bridging WhatsApp reactions to Matrix reactions?

**Comment by thebiblelover7** [comment]
Sorry, my bad... Should have checked more carefully.

**Comment by sumnerevans** [comment]
The backend ability has been in WA for a while, but the WA client teams hadn't gotten around to implementing it yet.
