### ISSUE TITLE
Sending messages fails with a 503 error

### ISSUE THREAD

**Issue by not-my-profile** [mautrix/whatsapp#496]
I can still receive messages but attempting to send a message (either PM or a group) fails with:

> ⚠️ Your message was not bridged: failed to get device list: failed to send usync query: info query returned status 503: service-unavailable

Updating the bridge to v0.4.0 did not resolve this problem. Deleting the session and creating a new session also did not resolve this problem.

**Comment by not-my-profile** [comment]
Is there anything I can do about this? Is that something that is known to happen?

**Comment by sumnerevans** [comment]
Someone could implement storing the device lists in the database (rather than in an in-memory cache). That would alleviate this specific issue.

But outages in WA are not something that can be solved by the bridge.

**Comment by kgncloud** [comment]
We could see that problem too and did switch in our image back to the latest published release. Building this repo from the current state does somehow produce this error or this is a coincidence form one moment where we downgraded our image.

**Comment by sumnerevans** [comment]
Restarting the bridge will cause all of the in-memory cache to be nuked, maybe you were getting lucky and hitting the cache before restarting the bridge. Then after the restart, it started to fail because the cached lists no longer existed.

**Comment by kgncloud** [comment]
@sumnerevans We will test that behavior further, but as you said it would be good if this data could be stored in the database. We use docker swarm mode and containers in general behave differently when the deamon knows it can create and destory containers from services without any problem ( theory)
