### ISSUE TITLE
Audio messages not working from all major Android apps

### ISSUE THREAD

**Issue by roughnecks** [mautrix/whatsapp#503]
Hello,

me and a friend tried audio messaging through mautrix and an iPhone. I am on mautrix and I'm the one sending audio messages through Android apps (Element, Fluffy and Schildi).
The results are varying from: No message received at all, empty audio message (plays but nothing is heard), empty message.
I tried sending a message from the Element Desktop app and that worked.

If I open my Whatsapp app and try to listen my own sent audio messages, I have similar results to what I described above for the end user.

To be noted that I also tried sending an audio message from mautrix-telegram with Schildi to the same person and he received an empty message as well. Don't ask me what exactly that was about, my friend is less tech savvy than me and I have not a clue :)

What I see in my Telegram is this:

![image](https://user-images.githubusercontent.com/1666536/170286691-dc086f35-8be4-44d0-b183-e4ccd0f2402b.png)

And I can hear it.

**Comment by tulir** [comment]
Seems to be working fine for me in all directions

**Comment by roughnecks** [comment]
Anything I can do to troubleshoot this?

**Comment by roughnecks** [comment]
![image](https://user-images.githubusercontent.com/1666536/170768667-873d04ca-34f0-473a-8347-9ec7212211d4.png)

This is how it looks in whatsapp for me (I'm the one sending the voice message through Schildichat).. There's nothing to be heard and in fact my friend replied "no niente" => "no, nothing".
