### ISSUE TITLE
Failed to send broadcast status

### ISSUE THREAD

**Issue by roughnecks** [mautrix/whatsapp#505]
Hi,

trying to send a picture as broadcast status message via Element Desktop and mautrix whatsapp v0.4.0 results in the following error:

`Your message was not bridged: failed to get broadcast list members: failed to get status privacy: info query returned status 404: item-not-found`

Logs: https://paste.debian.net/hidden/3b242de3/

**Comment by speatzle** [comment]
i have a user (which is using double puppeting) that also has this issue

**Comment by tulir** [comment]
Does it start working if you change status privacy settings on the mobile app?

**Comment by roughnecks** [comment]
> Does it start working if you change status privacy settings on the mobile app?

For me, status privacy is set to "contacts". What should I change that to? I only see "my contacts except.." and "share with..".

**Comment by speatzle** [comment]
> Does it start working if you change status privacy settings on the mobile app?

Yes that fixes it. It works no matter what you have set it to as long as you have changed it at least once.

**Comment by roughnecks** [comment]
Fixed for me too. Thanks
