### ISSUE TITLE
Double Puppeted Users get added to Other Users Status Broadcast Room's

### ISSUE THREAD

**Issue by speatzle** [mautrix/whatsapp#506]
When a Double Puppeted User Sends a Status Broadcast which is Received by another Bridge User in theyr Status Broadcast Room the Double Puppeted User can then See the Other Users Status Broadcast Room, All its History and Even Send status Broadcasts as that other User.

A Solution Would be for the Bridge to not use The Double Puppeted User's matrix account to Send the Status Broadcast to other Broadcast Rooms.

**Comment by tulir** [comment]
Oh that makes sense, it was reported in #371, but the description there made no sense, so I didn't bother looking into it :D

**Comment by verymilan** [comment]
Sadly a user just reported this happening to them today... the bridge was updated yesterday (it looks like the commit was for v0.6.0). :/
