### ISSUE TITLE
Backfill not starting

### ISSUE THREAD

**Issue by RobDiek** [mautrix/whatsapp#507]
Greetings

I tried many things on the config but whatever I choose the backfill doesnt start. The rooms are getting generated but even when I send a new message nothing happens. 

I attached my config - can someone please check if there is a bug in the version?

[config github.yaml.txt](https://github.com/mautrix/whatsapp/files/8794111/config.github.yaml.txt)

Thanks
Rob

**Comment by tulir** [comment]
I think the problem here was determined to be a synapse config issue (MSC2716 support not enabled)
