### ISSUE TITLE
Images without a valid mimetype are silently dropped

### ISSUE THREAD

**Issue by jaller94** [mautrix/whatsapp#510]
If I send a `m.room.message` with an image that has an invalid mimetype (e.g. `image/*`) the image is displayed in Element clients, but from a user's perspective the bridge will silently not be bridged without a notice.

```json
{
  "msgtype": "m.image",
  "body": "IMG_0001.jpg",
  "info": {
    "mimetype": "image/*",
    "w": 864,
    "h": 1152,
    "size": 115409
  },
  "url": "mxc://matrix.org/…"
}
```

**Comment by tulir** [comment]
You should probably just send valid mimetypes 🤔

The reason they're silently dropped is that they're actually not dropped and sent through just fine, but the receiver's client doesn't want to render it

**Comment by jaller94** [comment]
Makes sense.
We're also trying to identify the client that send this invalid mimetype. :+1:

Because the bridge is correctly bridge the event, I'll close this.

**Comment by jaller94** [comment]
Element Android client issue: https://github.com/vector-im/element-android/issues/2421

**Comment by tulir** [comment]
The bridge still isn't rejecting anything, but I guess it could have a whitelist for mimetypes to send as image/video/audio (and send the rest as documents)
