### ISSUE TITLE
Profile picture does not change

### ISSUE THREAD

**Issue by hooger** [mautrix/whatsapp#519]
I just fired up my android vm and saw that a profile picture changed (actually it happened more than 100 days ago), yet it didn't populate to the bridge, which however was restarted yesterday (and also a couple other times, like every two weeks).

Setup: Whatsapp runs in android VM, been fired up when the bot tells me to do so.
Bridge and everything else is managed via Slavi's playbook, last run happened on 2022.06.19. Current version of bridge: "dock.mau.dev/mautrix/whatsapp:v0.5.0"

Profile picture change should happen instantly---if I understand correctly---according to #301 so something seems to be wrong. Maybe there is some option that I have to opt-in?

Hope you can help me and also, keep up the great work! The bridge works really nice and reliable! Thank you for that!

**Comment by kgncloud** [comment]
We can confirm this bug and there is at least no logs that indicate a problem.
