### ISSUE TITLE
Disappearing messages compatibility

### ISSUE THREAD

**Issue by abdulocracy** [mautrix/whatsapp#520]
I use disappearing message timers in my chats, and when I send a message from the bridge it is incompatible with the timer and won't disappear after it expires. This message is shown next to any message sent from the bridge:
![Screenshot_20220620-214919_1](https://user-images.githubusercontent.com/25480267/174669544-3f64da06-21c8-407f-b693-164a80c8a063.png)

**Comment by tulir** [comment]
They're supported, but won't be enabled for old chats if you set up the bridge before they were supported. Toggling it on and off or relogining should make it work.

**Comment by abdulocracy** [comment]
I've tried logging in again, and I've even set up my Matrix server and mautrix-whatsapp from scratch, but it still is the same.
