### ISSUE TITLE
Presence WhatsApp -> Matrix

### ISSUE THREAD

**Issue by Tiebe** [mautrix/whatsapp#522]
I saw this was on the roadmap, and wanted to discuss if (and how) this will be possible, and when it will be done. I feel like this is one of the more crucial features for most users.

**Comment by Opisek** [comment]
Any updates? It seems it's been on the roadmap for years.

**Comment by PurpShell** [comment]
There are more intricacies. Privacy tokens, etc. 

Not even sure if whatsmeow has presence support in the first place (to an adequate level)

**Comment by PurpShell** [comment]
> Any updates? It seems it's been on the roadmap for years.
> 
> The underlying API does provide option for receiving presence updates: https://pkg.go.dev/go.mau.fi/whatsmeow#Client.SubscribePresence
> 
> The issue is that you likely don't want to subscribe to the presence of every user known to mautrix. Perhaps it's enough if we just listen to presence updates of users that you've created a private room with on matrix?

@tulir this function does not take a tcToken?

**Comment by tulir** [comment]
There are no plans for presence bridging currently

**Comment by Opisek** [comment]
In brief, what is the issue with privacy tokens? I would lilke to research potential solutions.
