### ISSUE TITLE
Weird character encoding on mobile, only on whatsapp bridge (Updated Element Android)

### ISSUE THREAD

**Issue by Mozoloa** [mautrix/whatsapp#535]
As said in the title, but it seems to only affect the single quote `'` and it turns it into `&#39;` and only when I recieve messages, it's not doing it on my messages, and on whatsapp the app, it's perfectly fine

**Comment by Mozoloa** [comment]
Weird as it seems it's not doing it with other bridges and my android app is updated

**Comment by Ulrar** [comment]
I can confirm, I had the same issue and it's fixed in the latest 1.4.28.
@Mozoloa It looks like the play store hasn't been updated yet but you can get the apk directly [here](https://github.com/vector-im/element-android/releases/tag/v1.4.28)

**Comment by Mozoloa** [comment]
> I can confirm, I had the same issue and it's fixed in the latest 1.4.28. @Mozoloa It looks like the play store hasn't been updated yet but you can get the apk directly [here](https://github.com/vector-im/element-android/releases/tag/v1.4.28)

Ho thanks a lot, that's a lot more usefull than the previous answer lmao, would you happen to know which one I should dl for a galaxy S10+ ?

**Comment by Ulrar** [comment]
One of the first two (arm), but which one I don't know. Probably the v8 !

**Comment by roughnecks** [comment]
Hopefully you read the BIG warning :)

**Comment by Mozoloa** [comment]
> Hopefully you read the BIG warning :)

Oh well I might wait for the next one lmao
