### ISSUE TITLE
The homeserver is outdated (server supports r0.6.1, but the bridge requires at least v1.1)

### ISSUE THREAD

**Issue by guyt101z** [mautrix/whatsapp#551]
Error.......The homeserver is outdated (server supports r0.6.1, but the bridge requires at least v1.1)

This is using the latest version of Synapse
curl http://localhost:8008/_synapse/admin/v1/server_version
{"server_version":"1.49.2","python_version":"3.6.9"}

*************Compiled binary
./mautrix-whatsapp
[Sep  8, 2022 19:11:42] [INFO] Initializing mautrix-whatsapp 0.6.1+dev.ec9e6d51 (Sep  8 2022, 19:03:02 with go1.18.5)
[Sep  8, 2022 19:11:42] [DEBUG] Initializing database connection
[Sep  8, 2022 19:11:42] [DEBUG] Initializing state store
[Sep  8, 2022 19:11:42] [DEBUG] Initializing Matrix event processor
[Sep  8, 2022 19:11:42] [DEBUG] Initializing Matrix event handler
[Sep  8, 2022 19:11:42] [INFO] Bridge initialization complete, starting...
[Sep  8, 2022 19:11:42] [DEBUG] Running database upgrades
[Sep  8, 2022 19:11:42] [Database/INFO] Database currently on v51, latest: v51
[Sep  8, 2022 19:11:42] [Database/StateStore/INFO] Database currently on v3, latest: v3
[Sep  8, 2022 19:11:42] [DEBUG] Checking connection to homeserver
[Sep  8, 2022 19:11:42] [Matrix/Bot/DEBUG] req #1: GET https://xxx.com/_matrix/client/versions?user_id=%40whatsappbot%3Axxx.com
[Sep  8, 2022 19:11:42] [Matrix/Bot/DEBUG] req #1 (/versions) completed in 97.383825ms with status 200 and 430 bytes of application/json body
[Sep  8, 2022 19:11:42] [FATAL] The homeserver is outdated (server supports r0.6.1, but the bridge requires at least v1.1)

************Pre-built Binary
 ./mautrix-whatsapp-amd64 
[Sep  8, 2022 19:21:40] [INFO] Initializing mautrix-whatsapp 0.6.1 (Aug 16 2022, 17:31:17 with go1.19)

DITTO Above

**Comment by tulir** [comment]
That's not the latest version of Synapse
