### ISSUE TITLE
Reply does not work anymore

### ISSUE THREAD

**Issue by DoM1niC** [mautrix/whatsapp#552]
![grafik](https://user-images.githubusercontent.com/1436958/189542326-6b5dd6a2-4527-4823-851b-0af0a5c8eafd.png)

**Comment by tulir** [comment]
That doesn't look related to replies, a temporary database or network issue, or a misconfiguration in the `error_after` config field is more likely. Logs will usually provide more details.

**Comment by DoM1niC** [comment]
> That doesn't look related to replies, a temporary database or network issue, or a misconfiguration in the `error_after` config field is more likely. Logs will usually provide more details.

works now THX for the notice !!!
