### ISSUE TITLE
When replying, backfilled message is shown empty on whatsapp side

### ISSUE THREAD

**Issue by krombel** [mautrix/whatsapp#564]
When I reply in whatsapp, I see the message I am replying to but when I reply on matrix side I only get an empty text (although the link to the previous message works as the jump works.
Here is an example how it looks in my test:
![WhatsApp Reply with empty text](https://user-images.githubusercontent.com/11167142/198829934-fc3d5612-0df3-49e5-abd1-b80e7fe81503.jpeg)

**Comment by tulir** [comment]
This is expected for all replies from Matrix. It shows up correctly for the recipients

**Comment by arikw** [comment]
@tulir can you please explain why it's expected?
