### ISSUE TITLE
Reaction bridging fails if the target message decryption failed initially

### ISSUE THREAD

**Issue by uumas** [mautrix/whatsapp#568]
So the message decryption from whatsapp failed initially but the bridge edited the message soon after:
![image](https://user-images.githubusercontent.com/10895201/201122244-91f83d57-88b5-4a0d-8f8b-6bee4acd5c9e.png)

When reacting to the edited event on Matrix, it fails with 
`⚠ Your reaction may not have been bridged: unknown target event $<eventid>`, where <eventid> is the id of the original event. When bridging reactions to that message from whatsapp, the reaction is applied to the message edit event, rather than the original so it's not visible in matrix.

So it seems Element reacts to the original message when it was edited, while the bridge reacts to the edit.

**Comment by nolimbsdotdev** [comment]
This issue is probably more general and is triggered when reacting to any message that is edited (thereby changing the eventid). I observed this on a message edited by the user (there was no encryption problem) just this morning. [mautrix-whatsapp v0.10.5].
