### ISSUE TITLE
Reactions to media captions fail

### ISSUE THREAD

**Issue by nolimbsdotdev** [mautrix/whatsapp#571]
Probably related to #568 .

If a user reacts to the caption of a media message then the action fails and the bridge bot reports:
```
This event could not be displayed
⚠ Your reaction may not have been bridged: unknown target event $....
```
Ideally, the reaction should be associated with the preceding media message.

**Comment by sumnerevans** [comment]
The correct fix for this is getting some actual caption support into the Matrix spec. The bridge already implements MSC2530 and MSC3552 and you can enable using them in the config: https://github.com/mautrix/whatsapp/blob/master/example-config.yaml#L298-L300, however most clients don't support either MSC.
