### ISSUE TITLE
eventauth: "@bot:homeserver-url" is not allowed to change their membership from "leave" to "join" as join rule "invite" forbids it`

### ISSUE THREAD

**Issue by jostreff** [mautrix/whatsapp#573]
Hi, currently I'm experiencing the described with 2 of bridge bots which I want to install on my dendrite-0.10.8 home server. 

Bridges are logging something like following:
`[Nov 30, 2022 16:03:16] [Matrix/DEBUG] Failed to join room !NlumPAgUuZeRP54s:matrix.ostreff.info as @whatsappbot:matrix.ostreff.info with invite from @jostreff:matrix.ostreff.info: failed to POST /_matrix/client/v3/rooms/!NlumPAgUuZeRP54s:matrix.ostreff.info/join: M_FORBIDDEN (HTTP 403): InputRoomEvents auth failed: InputRoomEventsResponse: eventauth: "@whatsappbot:matrix.ostreff.info" is not allowed to change their membership from "leave" to "join" as join rule "invite" forbids it`

How to reproduce the problem - just install it https://github.com/mautrix/whatsapp following the instructions described here https://docs.mau.fi/bridges/go/setup.html?bridge=whatsapp
On first attempt to connect to bridgebot it will crash with error above.

**Comment by tulir** [comment]
That's probably a bug in dendrite since the log says the bridge got an invite
