### ISSUE TITLE
Bot seems to process also commands from a different control room

### ISSUE THREAD

**Issue by jacotec** [mautrix/whatsapp#575]
I have seen an issue with the follwing scenario:

User 1 has a personal bridge room (and as a result a personal WhatsApp management room with the bot).

User "relay" is operating a relay bridge with a separate number, so that several people can answer and open chats with a common number. 
Therefore I have a node-red script which:

- invites other users when the relay user is invited from the bridge to a new room
- issues a "!wa set-relay" into every new room from the bridge
- echoes commands from users which are given inside the management room

User 1 is member of the users in the WhatsApp management room of the relay user.

The scenario:

- User 1 is in the management room of the relay user
- User 1 issues the command "!wa pm +49xxxxxxxx"
- (Background: The bot in the management room ignores the command as user1 is not "authorized" to give commands in this room)
- My node-red-script lets the relay user echo the command from user1
- As the relay user is the autohorized guy, the bridge creates the WA portal room.
- My node-red-script accepts the invitation as the relay user, issues the "!wa set-relay" and invites other users (also user 1) to the room.
- user 1 has accepted an invitation to a room from the WA bridge with the phone number he issued the "!wa pm" for

User1 now writes a message and I see that the chat does not (!) happen where it should (in the created global room by the relay user bridge), but only with his private phone number via his "own" bridge.

In the bridge logs I see that the bridge has invited user 1 two times: To a portal created by his private bridge *and* to the portal which my relay user has set up.

It appears that the private whatsapp bot of user 1 has "stolen" the "!wa pm" command which user 1 issues in a fully different room (the control room of the relay user).

The bot should not "steal" commands from the user in other control rooms and treat is as it would be in his own control room.

**Comment by tulir** [comment]
`!wa` commands are supposed to work in any room, unprefixed commands only work in the user's own management room.

You should probably use a different prefix for the relay management or forward them to a different room.
