### ISSUE TITLE
after using the command 'delete-all-portals' the bridge can not create whatsapp groups again

### ISSUE THREAD

**Issue by dasbenjo** [mautrix/whatsapp#576]
I played around with the bridge for a while and wanted to start fresh, so i typed in the command `logout` and `delete-all-portals`, but after I logged in again, I was not able to sync my WhatsApp Groups. The bridge can actually list them correctly and when I type the command `open [the group JID]` it tries to sync the group but fails, because it tries to use the old room ID from my Synapse Matrix Server, but this room is not there anymore. I made a quick screenshot of the logs:
![problem whatsapp bridge](https://user-images.githubusercontent.com/25540682/207625775-7b77f19b-6494-46c1-9c11-326eb6dfbf9d.jpg)

creating private chats with persons on whatsapp is no problem, but groups are not working anymore in this state

**Comment by tulir** [comment]
Probably https://github.com/mautrix/whatsapp/commit/1ce4e4a219a98c5843906b27ed0ef44172fd7a43, you'll have to re-delete the portals to make it work
