### ISSUE TITLE
Receiving WhatsApp messages creates empty room that causes Element to fail

### ISSUE THREAD

**Issue by JanMosigItemis** [mautrix/whatsapp#583]
Hi there,

I've got Dendrite + Mautrix Whatsapp here. The homeserver is running just fine and I can also talk to the WhatsApp bot. However, wenn receiving WA messages or issuing a `pm` command, the bot creates a room called "Empty room" which the Element web app does not seem to be able to load. Logs do not indicate any error. Is that a known behavior or is it caused by some misconfiguration? I just recently created a WA account and didn't allow the app to snuff through contacts. Is that a possible cause of trouble? Any help appreciated.

* Homeserver: Dendrite 0.10.9
* Mautrix: v0.8.0+dev.[acb056c8]

![image](https://user-images.githubusercontent.com/16935994/211157995-1d0db04b-1007-4ab8-9741-555a6c93f552.png)

**Comment by JanMosigItemis** [comment]
Update: I tried things on Android and this is working as expected. I even can access the created portal room on Element web app afterwards. Is it possible anyway to create a portal room via web app only or is a client running on a smartphone required for this?

**Comment by tulir** [comment]
Sounds like a Dendrite or Element bug

**Comment by vijfhoek** [comment]
I'm getting this too, with the Telegram bridge too, but accepting the request on any other client (Element iOS, Nheko, FluffyChat) all works fine. So I think it's an Element bug

**Comment by JanMosigItemis** [comment]
I think it'll be a good idea to provide the Element guys with a bug report on this. I'd do it myself but I am not sure whether or not there is sensible information in the debug data. Maybe someone else who knows better may open a bug there?
