### ISSUE TITLE
sync fail when bridge timezone differ from whatsapp client

### ISSUE THREAD

**Issue by rosbeef** [mautrix/whatsapp#585]
After a first sync bridging is working for 12 days then disconnect. 
In whatsapp android app, i can see an error that device is out of sync maybe due to an issue with my phone clock.
Is a difference between the client whatsapp and the mautrix bridge timezone could broke the sync ?
And why not to use, if possible, the whatsapp client time to sync datas to mautrix instead of mautrix bridge time (and that depending on the user)

**Comment by tulir** [comment]
It's unlikely to have anything to do with timezones. WhatsApp sometimes just randomly logs out linked devices, if it doesn't happen at least somewhat reproducibly, I'd assume it's a whatsapp bug
