### ISSUE TITLE
Call Notice for outbound calls through double puppeting

### ISSUE THREAD

**Issue by lewisdaly** [mautrix/whatsapp#596]
I see that setting `call_start_notices: true` in the config will enable call notices to be sent into the Matrix room. 

Is there a way to do this for outbound calls (from my linked WhatsApp account -> another WhatsApp account) to display a call notice in Matrix? I've got double puppetting enabled, and can see messages sent from WhatsApp puppetted into my Matrix room, but I'd like to get notices in Matrix for when I initiate a call from WhatsApp on my phone.

**Comment by tulir** [comment]
Not possible, WhatsApp doesn't send that info to other devices.

**Comment by lewisdaly** [comment]
Thanks for the heads up!
