### ISSUE TITLE
Enable message retention for Channels

### ISSUE THREAD

**Issue by nicolas-it** [mautrix/whatsapp#597]
Hi,
is there any chance to implement a configurable message retention for the StatusBroadcast-Channel?
https://github.com/matrix-org/synapse/blob/develop/docs/message_retention_policies.md#room-configuration

**Comment by aloiscochard** [comment]
It would be nice to be able to do that not only for the status broadcast, but also for the private messages.

Rational:
- When running a homeserver which is used both for puppeting and general matrix usage, one might one to have a default max_lifetime to be very small, it would be nice to be able to do that while still having a a high value for the bridged rooms
