### ISSUE TITLE
WhatsApp's Polls can have multiple choices

### ISSUE THREAD

**Issue by pree** [mautrix/whatsapp#599]
WhatsApp Polls can be configured to have multiple choices.
My bridge cannot handle this correctly, it doesn't show me the correct results and also only allows me to select a single entry.

![photo_2023-03-13_10-54-59](https://user-images.githubusercontent.com/9799276/224667599-371c5ac6-8bc2-44c8-9666-b84287ab3624.jpg)
![photo_2023-03-13_10-54-57](https://user-images.githubusercontent.com/9799276/224667606-3c2c0e22-7d44-4a22-ad1a-4b60adf1f001.jpg)

**Comment by conan747** [comment]
> That's a bug in your client

Is this true? Is there any client for which Whatsapp polls properly work? I use element and it doesn't work there.
