### ISSUE TITLE
Cannot enable double puppeting (M_UNKNOWN_TOKEN)

### ISSUE THREAD

**Issue by bahuma20** [mautrix/whatsapp#602]
Since the update to mautrix-whatsapp version 0.8.3 i cannot use the `login-matrix` command anymore. 
It fails everytime with the following error message:
`Failed to enable double puppeting: failed to GET /_matrix/client/v3/account/whoami: M_UNKNOWN_TOKEN (HTTP 401): Unknown token`

When i use the same command (with the same access token) for other bridges (telegram / signal) it works without problems.

I checked the changes between 0.8.2 and 0.8.3 and this commit could be related: https://github.com/mautrix/whatsapp/commit/1b31a36e602bc543419d54dc1af71c99607100a5

I can find this in the logs:
```
Sending request as_user_id=@bahuma20:noitl.space method=GET req_id=21 url=http://monolith:8008/_matrix/client/v3/account/whoami?user_id=%40bahuma20%3Anoitl.space

Request completed as_user_id=@bahuma20:noitl.space duration=0.521258 method=GET path=/v3/account/whoami req_id=21 response_length=53 response_mime=application/json status_code=401
```

I also tried to execute the GET request manually in postman with my access token as Bearer in the Authorization header and this works also.

I am using Dendrite 0.12.0 as homeserver.

**Comment by tulir** [comment]
See https://github.com/mautrix/discord/issues/70
