### ISSUE TITLE
Config option to disable disappearing messages

### ISSUE THREAD

**Issue by lewisdaly** [mautrix/whatsapp#609]
Is there any appetite to disable disappearing messages for the entire bridge?

For background: my WhatsApp/Matrix use case is for a highly regulated environment where we need to keep an audit trail of all messages that are sent between our users - so the ability for users to set messages to disappear after a certain time frame is a no-go for us.

**Comment by tulir** [comment]
You can set the redaction_retention_period in the synapse config to change how long redacted messages are kept: https://matrix-org.github.io/synapse/latest/usage/configuration/config_documentation.html#redaction_retention_period

And then use [MSC2815](https://github.com/matrix-org/matrix-spec-proposals/pull/2815) to be able to view redacted content in clients (although the client implementations of that aren't fully ready yet)

**Comment by lewisdaly** [comment]
Thanks @tulir - much appreciated
