### ISSUE TITLE
PNG to jpg convert while puppeting

### ISSUE THREAD

**Issue by gk-fschubert** [mautrix/whatsapp#612]
Whatsapp seems to support PNG images only as stickers. If you send a png via a matrix client, it arrives at the recipient, but cannot be displayed or downloaded. 

Since one does not want to pay attention to the file extension of his pictures, it would be good if the mautrix-whatsapp bridge automatically converts the pictures into jpg's.

**Comment by tulir** [comment]
WhatsApp supports png images

**Comment by gk-fschubert** [comment]
@tulir I don't think that is true. Every image which will be send by or trough whatsapp is converted to jpg.

**Comment by tulir** [comment]
The WhatsApp Android, iOS and web apps can handle png images just fine, both displaying and downloading.

**Comment by gk-fschubert** [comment]
Ok, the web version of android handles the PNG flawlessly(haven't used that for a while). 

But when i send the exact same image over element and the mautrix bridge to my whatsapp channel, i'm not able to see or download the file: 
![image](https://user-images.githubusercontent.com/41149338/234896177-4997c3b9-e977-4583-bbed-6ddf66770d78.png)
<img width="324" alt="image" src="https://user-images.githubusercontent.com/41149338/234896614-757451d2-4d99-4036-ac93-5ef3e3bd98d6.png">


They are displayed correctly in whatsapp web: 
![image](https://user-images.githubusercontent.com/41149338/234897003-a184d3ad-b767-4746-bd62-0d8d6ad94732.png)

**Comment by tulir** [comment]
That doesn't look related to the file type
