### ISSUE TITLE
qr code whatsapp

### ISSUE THREAD

**Issue by s4networks** [mautrix/whatsapp#622]
Tullir, I would like your help, I am using mautrix version 3.0 and it gives an error now I can no longer read the qr code to connect mautrix to whatsapp

**Comment by s4networks** [comment]
Give me a support channel, I can pay I really need the bridge working please

**Comment by s4networks** [comment]
Give me a support channel, I can pay I really need the bridge working please

**Comment by tulir** [comment]
The Matrix room is linked in the readme and it's also linked in the new issue view on github, but you probably just need to update the bridge
