### ISSUE TITLE
Reply messages in WhatsApp do not show original message

### ISSUE THREAD

**Issue by dkranke** [mautrix/whatsapp#624]
When replying to a message in the Beeper app using the WhatsApp Bridge, the original message does not appear in the recipient's WhatsApp app. This occurs despite the fact that the original message is correctly displayed in the Beeper app (as shown in Screenshot 1).

In the recipient's WhatsApp app, the reply message is linked to the original message, but the original message's content is not displayed, making it unclear what message is being responded to (as shown in Screenshot 2).

Screenshots:
![Reply in Beeper](https://github.com/mautrix/whatsapp/assets/30910026/9c6edddf-d467-4d24-98bb-9187a13511e7)
![Reply in Whatsapp](https://github.com/mautrix/whatsapp/assets/30910026/8971d8de-8f1d-4eeb-8cf5-93351e107cac)

**Comment by tulir** [comment]
It does appear in the recipient's WhatsApp app, it only doesn't appear in your own app.

**Comment by dkranke** [comment]
I got asked by a recipient to which message I replied, as it also was empty for them. Before that I also thought that it's only sender side

**Comment by tulir** [comment]
It definitely works on WhatsApp iOS, Android, Web and macOS Desktop Beta for me. They've even fixed the bug for your own messages on iOS and Web, so only Android shows empty replies like that for messages you sent.

It could be broken on WhatsApp Windows, can't test that one myself, but I'd expect them to fix the bug on their side eventually.

**Comment by JAicewizard** [comment]
> It definitely works on WhatsApp iOS, Android, Web and macOS Desktop Beta for me. They've even fixed the bug for your own messages on iOS and Web, so only Android shows empty replies like that for messages you sent.

For me the recipient was on android. Maybe it makes a difference if it is a groupchat? or a community chat?

**Comment by tulir** [comment]
That doesn't make any difference. It's only broken for recipients on the new windows desktop app

**Comment by HandyHat** [comment]
It's still broken on Android too

**Comment by tulir** [comment]
Works fine for me, please provide proof if it's actually broken.

Cases that are known and don't matter (do not report these):

* Being broken for the sender (on Android)
* Being broken for recipients on Windows desktop
* Being broken for recipients who can't see the original message (e.g. replying to a message which was sent before they joined the group)

**Comment by HandyHat** [comment]
Apologies - yes it is only limited to the cases you've described

**Comment by FlafyDev** [comment]
> Works fine for me, please provide proof if it's actually broken.
> 
> Cases that are known and don't matter (do not report these):
> 
>     * Being broken for the sender (on Android)
> 
>     * Being broken for recipients on Windows desktop
> 
>     * Being broken for recipients who can't see the original message (e.g. replying to a message which was sent before they joined the group)

So why is the issue not open to track and eventually fix these problems?
