### ISSUE TITLE
Backfill does no longer work with Matrix Synapse

### ISSUE THREAD

**Issue by derritter88** [mautrix/whatsapp#628]
Hello there,

I have been using this bridge for a year without any problems.
Initially I configured my Matrix homeserver as mentiond with 
```
experimental_features:
  msc2716_enabled: true
```
which still works.

But since the upgrade to 1.87.0 the bridge does no longer work if `backfill: true`.
The log says:
```
mautrix-whatsapp-amd64[634328]: Jul  6, 2023 13:08:05 FTL Backfilling is enabled in bridge config, but homeserver does not support MSC2716 batch sending
```

**Comment by tulir** [comment]
The master branch has legacy backfill support

**Comment by derritter88** [comment]
So what is the correct approach?
Leaving backfill: false?

**Comment by sumnerevans** [comment]
I think that all of these settings should still work: https://github.com/mautrix/whatsapp/blob/master/example-config.yaml#L130-L155

It will just backfill everything all at once on portal creation, instead of incrementally backfilling like is supported via Beeper.

**Comment by derritter88** [comment]
Unfortunately backfill: true does no longer work with the current Matrix Synapse server.
I installed the update two days ago on my Ubuntu 22.04 VM and yesterday I recognised that Mautrix Whatsapp service was no longer running due to the above mentioned error message.

**Comment by sumnerevans** [comment]
You probably aren't using the `master` branch, then.

**Comment by derritter88** [comment]
I am using the precombiled version from the release section.
For Synapse I am using the official Ubuntu repository

**Comment by sumnerevans** [comment]
The release is not `master`

![image](https://github.com/mautrix/whatsapp/assets/16734772/bd620670-046e-4c4d-aab1-4c2c4654426f)

notice there are 18 commits to `master` since that release

**Comment by derritter88** [comment]
I see - are there any plans to release another precompiled version?

**Comment by sumnerevans** [comment]
Eventually, yes. If you really don't want to compile it yourself, you should be able to download the latest executable from CI if you want: https://mau.dev/mautrix/whatsapp/-/jobs/35335 (choose which architecture on the right)

**Comment by derritter88** [comment]
Thanks @sumnerevans - that did  the trick. 
The current binary file from there is running with backfill: true.
