### ISSUE TITLE
Http 500 Error on POST pictures

### ISSUE THREAD

**Issue by muellerjoel** [mautrix/whatsapp#632]
![IMG_1388](https://github.com/mautrix/whatsapp/assets/76882403/8c9adbe9-0e1a-4b1d-9324-9caf74fe7d6a)

**Comment by tulir** [comment]
That's an error in your homeserver

**Comment by muellerjoel** [comment]
Are you shure? In private whatsapp rooms the pictures ate shown normal

**Comment by tulir** [comment]
Yes, that's what "internal server error" means: the server that handled the request is broken. `/_matrix/media/v3/upload` is usually handled by the homeserver, or if you have a separate media repo then by that server.

**Comment by muellerjoel** [comment]
Ok. Wired. Why should video work in the same  broadcast room and pictures not and so pictures in normal bridge rooms too.

**Comment by muellerjoel** [comment]
Ok i found out the error it’s about sqlite version. Sqlite 3.40 is all ok with 3.42 the internal error shows up

**Comment by Happyfeet01** [comment]
hi @muellerjoel 

have the same error message with the generated QR Code. Can you tell me how you downgrade the Sqlite Version?

ERR Failed to upload QR code: failed to POST /_matrix/media/v3/upload: M_UNKNOWN (HTTP 500):

**Comment by muellerjoel** [comment]
@Happyfeet01 

Hi
Which Distro do you have? 

For Arch Linux  go to https://archive.archlinux.org  browse s and go to the right sqlite version copy the url

do curl -o URL and then pacman -U sqlite-XXXXX

Restart synapse and the bridge with systemd service

Cheers

**Comment by uvolmer** [comment]
I had the same error with a matrix synapse installed via pip.
Posting images to unencrypted rooms (like whatsapp) was not possible.
For me, this was solved by

pip install -U pillow==9.5.0

**Comment by Happyfeet01** [comment]
Thanks. That Works

**Comment by BlackLight** [comment]
Downgrading Pillow worked for me (but not downgrading SQLite).

Does anyone know why this bug started occurring in the first place? I can't see any details from the logs, and, even though downgrading Pillow is a workaround that works for now, I can't keep it on a lower version without breaking other Python system packages.

**Comment by uvolmer** [comment]
The synapse bugreport of the pillow bug is below.
As far as I know, it is fixed in synapse version 1.88.0

https://github.com/matrix-org/synapse/pull/15876
