### ISSUE TITLE
Sending certain file types Matrix→WhatsApp does not work

### ISSUE THREAD

**Issue by vncnt-dev** [mautrix/whatsapp#633]
While sending certain file types, such as photos and .txt files, works without any problems, files with types like .zip cannot be opened from WhatsApp when sent from Matrix.

Steps to reproduce:
- send a .zip file using from Matrix to a WhatsApp Chat.
- try to open the file from an official WhatsApp Client (f.e. the App)

**Comment by tulir** [comment]
Sounds like a WhatsApp issue, probably not related to the bridge

**Comment by vncnt-dev** [comment]
But I can send these types of files from an official WhatsApp Client without a problem.

**Comment by tulir** [comment]
There's no problem sending them from the bridge either. All the native apps act the same way regardless of whether the file was sent over the bridge or from another native app.

**Comment by LeviWenzel** [comment]
I'm encountering the same issue. I've generated an example file (as shown below). When I send it as a .txt file, everything works perfectly. However, if I remove the file extension (or alter it to something "non-standard" like .md), the Application abruptly exits the chat when attempting to open the file. In the video below, you can see the different behavior between "Sending a file from the native app" and "Sending the file from Elements."

[testAttachment.txt](https://github.com/mautrix/whatsapp/files/12739971/testAttachment.txt)

https://github.com/mautrix/whatsapp/assets/77998138/b867bfff-68d5-47a1-a564-b4e5bf21c434
