### ISSUE TITLE
Support logging into multiple whatsapp accounts

### ISSUE THREAD

**Issue by ayushin** [mautrix/whatsapp#634]
This would be very useful when the same matrix user has a personal and a business whatsapp account.

Ideally we could have separate spaces for separate whatsapp accounts so the bot would know which one is which

**Comment by baerenmarke90** [comment]
+1 that would be awesome

**Comment by s3ase** [comment]
If you run your own server, and doing docker compose route, just create other WhatsApp bridge container with new name (and change info in config - whatsappbotwork whatsappbotpersonal)
