### ISSUE TITLE
User messages missing in group chats

### ISSUE THREAD

**Issue by aureliensoria** [mautrix/whatsapp#638]
Hello,

I have encountered this issue two times in the last weeks.
On some group chats, all the messages of a specific user whatsapp user be missed by the bridge and won't appear in the matrix chat while they exist on the whatsapp group chat.

I tried restarting the bridge container, I think it resolves it but the bug appears again elsewhere after a few days.

Here is an example of the issue:
Whatsapp: 
![whatsapp](https://github.com/mautrix/whatsapp/assets/17644179/c25c305e-02bd-40df-9ccb-41efc78fbece)

Element:
![element](https://github.com/mautrix/whatsapp/assets/17644179/2f71b32f-c90d-4361-b002-1790e20fbc52)

The thumb up is also from R user.

If you need any information, don't hesitate. 
Thank you !

**Comment by jon02ch** [comment]
I haave a similar problem, I as well can't send pm's to that user? how is o for you @aureliensoria

**Comment by th0mcat** [comment]
I'm seeing the same issue.  It appears the person whose messages that  are not being bridged is the person that created the group chat.  @jon02ch @aureliensoria Can you confirm that the person whose messages you aren't getting is the person who created the chat?

**Comment by ptrne** [comment]
Hi,

I am experiencing the same issue ever since I am using mautrix almost a year ago. It does always happen with the same users but I cannot confirm this only happens to the creators of the group. As a wild guess, it may be that those users are using an old WhatsApp client or have some weird settings?

Anyway, would be great if this was solved, because it considerably reduces the usefullness of the bridge.

**Comment by th0mcat** [comment]
The problem for me was the bridge was trying to create already existing users.  I had to delete the user from the `user` and the `profiles` tables in my synapse database.

**Comment by ptrne** [comment]
Hm don't know about that. I am using mautrix together with Dendrite. Does Dendrite use the same DB layout?

**Comment by ptrne** [comment]
Happy to say that this issue seems to have been fixed with the last Dendrite release 0.13.6.
