### ISSUE TITLE
Login with phone number

### ISSUE THREAD

**Issue by pablotoribio-beta** [mautrix/whatsapp#639]
Hi, im new with this bridge, i followed the instructions and wanted to log in with whatsapp.
I use a VM for whatsapp and a camera is not an option for scan the QR code, following the instruction at https://docs.mau.fi/bridges/go/whatsapp/authentication.html says since the version 0.10.0 is possible to log in with a phone number.
I could not find this version, the latest is 0.9.0 and the login with the number gives me a QR code.
How i can procced for log in by code?
Thanks you in advance.

**Comment by olmari** [comment]
0.10.0 is not released yet, so you'd need to use git master version (and compile it) for that.

Though VM's can use usb-camera on the "guest" with computer you're using the VM with (at the time of attached session), but yes it _is_ fiddly at best...
