### ISSUE TITLE
Code login error

### ISSUE THREAD

**Issue by pablotoribio-beta** [mautrix/whatsapp#645]
When i try to login by 8 digit code i got this error:
Failed to start phone code login: info query returned status 400: bad-request

in the config file i setup this parameters:

# Config for things that are directly sent to WhatsApp.
whatsapp:
    # Device name that's shown in the "WhatsApp Web" section in the mobile app.
    os_name: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/116.0
    # Browser name that determines the logo shown in the mobile app.
    # Must be "unknown" for a generic icon or a valid browser name if you want a specific icon.
    # List of valid browser names: https://github.com/tulir/whatsmeow/blob/efc632c008604016ddde63bfcfca8de4e5304da9/binary/proto/def.proto#L43-L64
    browser_name: firefox

Im doing something wrong?

**Comment by tulir** [comment]
It's mentioned in the release notes and was already fixed

**Comment by rnhmjoj** [comment]
What is this "specific way" you mention in the release notes?

**Comment by rnhmjoj** [comment]
Ok, found this [commit](https://github.com/mautrix/whatsapp/commit/4ad2a9e318b9dee29db7a2a82b38f1147e29ebc6): setting `os_name: "Chrome (Linux)"` worked.
