### ISSUE TITLE
Own messages sent from WhatsApp don't appear in DMs when double puppeting is disabled

### ISSUE THREAD

**Issue by gabrc52** [mautrix/whatsapp#648]
When double puppeting is disabled:

* When I send a message from WhatsApp (or another WhatsApp client such as Beeper's modified Mautrix-WhatsApp), the message is properly bridged to an instance of Mautrix-WhatsApp without double puppeting, but only if it is a group chat. On DMs, the ghost user doesn't send my messages and instead those messages are just missing from the history.

**Comment by tulir** [comment]
That's expected, you should enable double puppeting if you want to send messages from other WhatsApp clients
