### ISSUE TITLE
[QUESTION] Do I Really Need To Be Homeserver Admin

### ISSUE THREAD

**Issue by thealidev** [mautrix/whatsapp#651]
I am very curious about `mautrix matrix bridges`
I like to ask if i use a public Homeserver like `matrix.org`
Will it work

According to matrix api
You don't have to homeserver admin

So i am just curious

Kindly answer my question

Regards
Muhammad Ali

**Comment by sumnerevans** [comment]
The issue tracker is not the place to ask questions about setup. Please use the Matrix room: https://matrix.to/#/#whatsapp:maunium.net

You need to be able to add the bridge registration file to the homeserver, which requires that you are a homeserver administrator or have a homeserver administrator who is willing to install the registration file for you.
