### ISSUE TITLE
Support for unix sockets

### ISSUE THREAD

**Issue by Sir-Photch** [mautrix/whatsapp#652]
For a self-hosted scenario, it is quite likely that both homeserver and bridge are operated on the same server. For this, it would be quite handy if both the bridge could connect through the unix-socket of the homeserver via the `address`-parameter in the configuration and the homeserver could make use of a socket opened up by the bridge to connect to the appservice.

What do you think?

**Comment by tulir** [comment]
Unix sockets are already supported

**Comment by Sir-Photch** [comment]
And how do you specify them?
