### ISSUE TITLE
puppet event not correct

### ISSUE THREAD

**Issue by yixiangfeng** [mautrix/whatsapp#653]
version v0.10.2
synapse: v1.59

step:

1. input command in bot `login`
2. scan qr code
3. after scan qr code input command `login-matrix <access-token>`
4. portals keep creating and joining.
5. click room see the room message

web using `app.element`

```
---------------Tody---------------
user1
hello
--------------Mon, Oct 3, 2022-----------------
+85212345678 (WA)
Hi all, 
```
the user1 message is send in my device and the send time is before Mon, Oct 3, 2022 but this `event` `origin_server_ts: 1695893327191` 

this behavior is correct or wrong i expect the `hello` event `origin_server_ts`is same with whatsapp send time

**Comment by tulir** [comment]
That's expected unless you modify synapse to allow your user to set timestamps, or use the new appservice method for double puppeting: https://docs.mau.fi/bridges/general/double-puppeting.html#appservice-method-new

**Comment by yixiangfeng** [comment]
@tulir what the mean `modify synapse to allow your user to set timestamps`? in the synapse config.yaml ?
