### ISSUE TITLE
Whatsapp -> Matrix: Polls not showing as polls but as a numbered list

### ISSUE THREAD

**Issue by wrjlewis** [mautrix/whatsapp#654]
Polls created in whatsapp, and then bridged to Matrix, are showed as a numbered list, rather than a poll, in Element Web (desktop) and Element X. 

<img width="113" alt="image" src="https://github.com/mautrix/whatsapp/assets/1543626/e34e86f0-1a50-4884-8a8c-20b25194c262">

This may not be a bug, and could be the best available workaround, is that the case?

**Comment by wrjlewis** [comment]
Ps great work on the bridge, I'm enjoying using it so far, thanks.

**Comment by tulir** [comment]
https://github.com/mautrix/whatsapp/blob/v0.10.2/example-config.yaml#L306

**Comment by wrjlewis** [comment]
Ah thank you, didn't see that, works perfectly
