### ISSUE TITLE
Matrix -> WhatsApp sync user profile pictures

### ISSUE THREAD

**Issue by Sir-Photch** [mautrix/whatsapp#656]
I suggest we add synchronization of matrix-avatar and whatsapp-avatar, that means: changes to the matrix-user's avatar will be synced to whatsapp. (Optionally behind a config flag.)

Setting the whatsapp avatar is possible according to https://github.com/tulir/whatsmeow/issues/325#issuecomment-1407486249

**Comment by Tycho-S** [comment]
It would be great if this were optional, because not in all cases it's actually something I would like. Especially in the cases of bridging multiple whatsapp accounts with one matrix account.

I'm actually quite happy that no bridges do this right now.

**Comment by Sir-Photch** [comment]
I'm sure this can be implemented in a configurable way
