### ISSUE TITLE
Sending Files Issue

### ISSUE THREAD

**Issue by LeviWenzel** [mautrix/whatsapp#657]
I'm encountering the same issue as in https://github.com/mautrix/whatsapp/issues/633.
I've generated an example file (as shown below, just a .txt with the word "Test" in it). When I send it as a .txt file, everything works perfectly. However, if I remove the file extension (or alter it to something "non-standard" like .md), the Application abruptly exits the chat when attempting to open the file. In the video below, you can see the different behavior between "Sending a file from the native app" and "Sending the file from Elements."

[testAttachment.txt](https://github.com/mautrix/whatsapp/files/12841691/testAttachment.txt)

https://github.com/mautrix/whatsapp/assets/77998138/3c1d6a00-8533-4d39-89d6-8be2a02e9e7c

**Comment by tulir** [comment]
WhatsApp still doesn't crash, although I did notice a minor difference if the sending Matrix client forgets to set a mime type. The only difference is which apps it shows as options for opening the file on android (no mime -> probably always no apps). Only affects extensionless files at least on element web, .md/.zip/etc work fine
