### ISSUE TITLE
Show messages sent via WhatsApp app

### ISSUE THREAD

**Issue by dylanmorroll** [mautrix/whatsapp#658]
I hope I'm writing this in the right place - I recently tried out Element One to see what the bridging was like - and if I'm correct it uses the mautrix bridges?

But yeah the main thing I noticed that's a bit of a pain, is if I send a message from WhatsApp on my phone, it doesn't appear in Element. Would be great if this was possible to implement! It makes it a bit hard to reply from Element when I'm back on my laptop as I'm missing some of the context.

**Comment by tulir** [comment]
https://docs.mau.fi/bridges/general/double-puppeting.html
