### ISSUE TITLE
Tagging users doesn't work 

### ISSUE THREAD

**Issue by gouthamravee** [mautrix/whatsapp#659]
When tagging users, it doesn't get bridged properly to whatsapp. 

On the whatsapp side, instead of a proper tag the message is plain text that's the username + (WA). 

This is on the latest version of Synapse, Element, and the Mautrix Whatsapp bridge.

**Comment by tulir** [comment]
Works fine for me. What does the event source on Matrix contain?

**Comment by gouthamravee** [comment]
Tested just now 

```
{
  "type": "m.room.message",
  "content": {
    "msgtype": "m.text",
    "body": "Neela S (WA) ",
    "format": "org.matrix.custom.html",
    "formatted_body": "Neela S (WA) ",
    "m.mentions": {
      "user_ids": [
        "@whatsapp_1<redacted-number>:my.domain"
      ]
    }
  }
}
```

**Comment by tulir** [comment]
There's no mention in `formatted_body`, so seems like a client bug. It's supposed to be `<a href="https://matrix.to/#/@whatsapp_...">Neela S (WA)</a>`

**Comment by gouthamravee** [comment]
Thank you, what client are you using? I'm using Element and I see this issue across desktop, web, and android.

**Comment by tulir** [comment]
It works for me on element web. Looks like element x android doesn't do mentions at all yet. Also afaik only element web/desktop has `m.mentions` implemented, not sure how that would fail to add the proper formatted body

**Comment by gouthamravee** [comment]
Is there a setting within the app that enables/disables mentions? I tried to look through but didn't see anything. 

Tbf, this isn't the only issue I have, so I figure a full reinstall from scratch would be the way to go.

**Comment by niebloomj** [comment]
Sounds like we can close this ticket
