### ISSUE TITLE
Bridge sends invalid stickers

### ISSUE THREAD

**Issue by jplatte** [mautrix/whatsapp#662]
Apparently, this event (seemingly with event ID and possibly other things redacted) was sent by mautix-whatsapp:

```json
{
  "room_id": "censor",
  "type": "m.sticker",
  "content": {
    "body": "image.webp",
    "file": {
      "hashes": {
        "sha256": "censor"
      },
      "iv": "censor",
      "key": {
        "alg": "A256CTR",
        "ext": true,
        "k": "censor",
        "key_ops": [
          "encrypt",
          "decrypt"
        ],
        "kty": "oct"
      },
      "url": "mxc://fuo.fi/censor",
      "v": "v2"
    },
    "info": {
      "h": 190,
      "mimetype": "image/webp",
      "size": 29502,
      "thumbnail_file": {
        "hashes": {
          "sha256": "censor"
        },
        "iv": "censor",
        "key": {
          "alg": "A256CTR",
          "ext": true,
          "k": "censor",
          "key_ops": [
            "encrypt",
            "decrypt"
          ],
          "kty": "oct"
        },
        "url": "mxc://fuo.fi/censor",
        "v": "v2"
      },
      "thumbnail_info": {
        "h": 190,
        "mimetype": "image/webp",
        "size": 29502,
        "w": 190
      },
      "w": 190
    }
  }
}
```

(reported [here](https://matrix.to/#/!amwlFMejXQcoCxNYHH:matrix.org/$0W2SEUCdfvnHRjgg3amPuhP-eISgHpxUKJ3ACcl8GT8?via=matrix.org&via=element.io&via=beeper.com) in the Element X iOS room)

It has a `url` field, but nested under `content` -> `file` while [the spec](https://spec.matrix.org/latest/client-server-api/#msticker) says that `m.sticker` must have a `url` under `content` directly.

**Comment by tulir** [comment]
That's encrypted, not invalid

**Comment by jplatte** [comment]
Is there an MSC for that?

**Comment by tulir** [comment]
More of a spec omission/mistake than a MSC. Stickers are just `m.image`s with their own event type, so all the same fields apply and `file` was probably just missed while copying the schema. The `info` schema was not duplicated, so `thumbnail_file` is already there.

**Comment by jplatte** [comment]
Okay, thanks for the quick replies.
