### ISSUE TITLE
Pictures are not synced with matrix/synapse and an error message is shown

### ISSUE THREAD

**Issue by Letgamer** [mautrix/whatsapp#663]
After setting up the latest version of element, synapse and the whatsapp-bridge via docker-compose no Pictures are synced and cannot be recieved. Instead following message is shown:

> Failed to bridge media: failed to upload media: failed to POST /_matrix/media/v1/create: M_UNRECOGNIZED (HTTP 404): Unrecognized request

It seems to be that the whatsapp-bridge is utilizing the new matrix client-server-api from matrix 1.7, which is not yet supported by synapse and therefore a error error is returned, because the endpoint doesn't exist.

See also: https://github.com/matrix-org/synapse/issues/15661

**Comment by tulir** [comment]
That's a config option https://github.com/mautrix/whatsapp/blob/master/example-config.yaml#L17-L18

**Comment by Letgamer** [comment]
Thank, I appreciate your answer very much, I hope you have a nice day :)
