### ISSUE TITLE
Own sent messages are not synced

### ISSUE THREAD

**Issue by Letgamer** [mautrix/whatsapp#664]
I am afraid I have to write another bugreport.
I have enabled double puppeting and set everything up, but I realized that my own sent messages are not synced and in the history. Probably it can be configured through the config file, but I can't seem to find the setting and no other bug report where this is mentioned.
 I would greatly appreciate any help :)

**Comment by aquarat** [comment]
I'm experiencing the same issue using the `latest` docker image.

**Comment by Konubinix** [comment]
Same here :-)

**Comment by mlafuente-ssi** [comment]
Same here, and it seems to be happening on Telegram and Messenger too.

**Comment by niebloomj** [comment]
I'm having the same issue. This seems like a big enough bug that id expect more activity. Either from users or a dev. How are other people able to use this? Maybe it's a configuration issue and not a global bug?

**Comment by storm1er** [comment]
Same here, backfill feels useless without sent messages.

I tried multiple backfill options but nothing worked :/

**Comment by niebloomj** [comment]
I got it working by having double puppeting enabled and then doing the backfill

**Comment by storm1er** [comment]
https://docs.mau.fi/bridges/general/double-puppeting.html

> In most of the bridges, this is necessary to bridge DMs you send from other clients to Matrix.

'kay
