### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by cyberb** [mautrix/whatsapp#665]
```
maunium.net/go/mautrix-whatsapp
whatsapp/portal.go:335:39: cannot use (*Portal)(nil) (value of type *Portal) as bridge.MembershipHandlingPortal value in variable declaration: *Portal does not implement bridge.MembershipHandlingPortal (wrong type for method HandleMatrixInvite)

		have HandleMatrixInvite(bridge.User, bridge.Ghost)

		want HandleMatrixInvite(bridge.User, bridge.Ghost, *event.Event)
```

**Comment by tulir** [comment]
Did you somehow tell the compiler to ignore dependency versions? 🤔

**Comment by cyberb** [comment]
Oh, sorry I was using go.work with latest code from mautrix-go lib go get my unix socket changes (as they were not referrnced by whatsapp) let me try to use the one from dependency.

I guess currently HEADs are not compatible, is it normal?

**Comment by cyberb** [comment]
Ok, reverting back to dependency version fixed it, sorry again.
