### ISSUE TITLE
Not compatible with latest sqlite

### ISSUE THREAD

**Issue by muellerjoel** [mautrix/whatsapp#667]
Hi 
the bridge 0.10.4  isnt compatible with lastest sqlite version.

the mediafiles like images won't be bridged

**Comment by tulir** [comment]
The bridge never uses system libraries and this issue doesn't have any details.

**Comment by tulir** [comment]
Not related to sqlite in any way, but I did notice a bug where network errors were masked by the file too short, so that's fixed now

**Comment by muellerjoel** [comment]
Thanks.
Last time it was related to sqlite. So I thought would be the same.
