### ISSUE TITLE
Douple puppeting ping-matrix bug

### ISSUE THREAD

**Issue by Letgamer** [mautrix/whatsapp#668]
![image](https://github.com/mautrix/whatsapp/assets/62446107/e59a8970-1518-4466-ba65-5a9b2448e921)
douple pupetting is fully configured, despite ping-matrix not working

**Comment by tulir** [comment]
The command is `login-matrix`, not `login matrix`

**Comment by Letgamer** [comment]
Then I get the following error: 
Failed to enable double puppeting: failed to unmarshal response body: invalid character 'I' looking for beginning of value
