### ISSUE TITLE
Personal filtering spaces are not enabled

### ISSUE THREAD

**Issue by Letgamer** [mautrix/whatsapp#669]
![image](https://github.com/mautrix/whatsapp/assets/62446107/d3203f10-8121-41bb-9b9d-33b9a5efa12e)
Space creation via sync command is not working

**Comment by tulir** [comment]
That is expected if you don't enable it in the config

**Comment by Letgamer** [comment]
where can i enable it, I use synapse?

**Comment by Letgamer** [comment]
nvm, fount it, I thought I had to enable it in homeserver.yaml, thanks for the help👍
