### ISSUE TITLE
How to make the bot invite all admins on private incoming whatsapp message?

### ISSUE THREAD

**Issue by CyberPingU** [mautrix/whatsapp#676]
Hello all,
as per title: how can I do to make the mautrix-whatsapp bot invite ALL its admins inside the room that the bot creates when a direct message from whatsapp incomes?
Is there a way?

**Comment by tulir** [comment]
You can make a bot that invites specific users and sends the command to enable relay mode, then sign into the bridge with that bot. https://github.com/maubot/supportportal can be used as inspiration (but should not be used directly as it's unmaintained)
