### ISSUE TITLE
Client warning icon: session not trusted

### ISSUE THREAD

**Issue by ItsQuadrus** [mautrix/whatsapp#689]
This red icon appears on messages. Is there a way to make the bridge "verify" its own session?
![Screenshot_20240401-193333](https://github.com/mautrix/whatsapp/assets/89267584/3abf48b5-2de3-4da8-9ae3-a8ab8103cecc)

**Comment by tulir** [comment]
https://docs.mau.fi/bridges/general/troubleshooting.html#can-i-verify-the-bridge-e2ee-session

**Comment by ItsQuadrus** [comment]
Apologies! I missed that one.
