### ISSUE TITLE
Dendrite homeserver not supported

### ISSUE THREAD

**Issue by wietsedv** [mautrix/whatsapp#693]
When I try to use this bridge with Dendrite I get the following error:

```
The homeserver is outdated (supported spec versions are below minimum required by bridge) bridge_requires=v1.4 server_supports=v1.2
```

This would be related to the minimum Matrix spec version [bump](https://github.com/mautrix/go/blob/master/CHANGELOG.md) in the go backend.

@tulir I am aware that Dendrite is experimental, but you seem to have the intention to make this work: https://github.com/matrix-org/dendrite/pull/3316

I am on Dendrite 0.13.7 and Mautrix-Whatsapp 0.10.7.

**Comment by tulir** [comment]
There's a flag that can be used to ignore advertised versions

**Comment by hkdb** [comment]
@tulir is there any documentation or snippet somewhere on how one might be able to set the flag to ignore advertised versions?  I am on the same boat as @wietsedv and as of yesterday, the only versions that work are v0.10.6 and v0.10.7 yet both are exiting with the same error message saying that homeserver is outdated. Thanks!

**Comment by andrewmerrell** [comment]
Use `--ignore-unsupported-server`, worked for me recently eg.

```
/usr/bin/mautrix-whatsapp` -c /data/config.yaml -r /data/registration.yaml --ignore-unsupported-server
```

https://github.com/mautrix/go/blob/2195043eba98e7123c90006996a81ec3f94e83fe/bridge/bridge.go#L50
