### ISSUE TITLE
websocket disconnected before info query returned response

### ISSUE THREAD

**Issue by michelleDeko** [mautrix/whatsapp#696]
Hi, 

I woke up today with the bridge not working anymore. I was trying to reconnect it, but it didn't work. Now I tried logging out and loggin in again and now I'm getting the following error:
Failed to start phone code login: websocket disconnected before info query returned response

Already tried updating and restarting the service, but it still doesn't work.

I'm also getting this error:
Bridge is using outdated WhatsApp web protocol (2.2329.9, latest is 2.3000.0)

Does anyone have an idea on how to fix this?

**Comment by gianklug** [comment]
currently getting a

⚠ Your message was not bridged: you are not connected to WhatsApp

not sure if it's just a temporary thing, not near the phone with whatsapp rn to reconnect

**Comment by tulir** [comment]
Outdated versions of the bridge aren't supported

**Comment by michelleDeko** [comment]
> Outdated versions of the bridge aren't supported

I'm using version v0.9.0+dev.5c8c736c, so I think I'm using the newest version?

**Comment by gianklug** [comment]
@tulir also happening to me on latest.

**Comment by michelleDeko** [comment]
@gianklug yup, exactly the same error I'm getting in the console

**Comment by tulir** [comment]
5c8c736c is a 10 month old version, nowhere near latest.

> also happening to me on latest.

your logs indicate you're using a 5 month old version (2.2353.59 was latest in december: https://github.com/tulir/whatsmeow/commit/9d803dd927351f5684accc00c0d0febd47fe3876)
