### ISSUE TITLE
Upgrade Error "pickled object is too new"

### ISSUE THREAD

**Issue by atroposfate** [mautrix/whatsapp#700]
I had a old version of the bridge and received an error recently that saved "failed to log-in: outdated client. The bridge must be updated to continue."
I tried to update with a git pull but was getting an error about using the master branch
I just cloned a new version and when I went to run ./build.sh I didn't have g++ installed. I don't believe I would have uninstalled it so must have been a new requirement relative to my old version. I installed it and went through the install steps of the bridge and was processed without error, updated, replaced the files but when I start the bridge I'm getting the following error:

2024-05-22T20:41:04-06:00 FTL Error initializing end-to-bridge encryption error="the pickled object is too new"

I saw another example of someone with the same error but was related to downgrading one of their libraries which shouldn't have happened.

**Comment by halkeye** [comment]
What version did you clone? go shouldn't need g++ installed.

https://github.com/mautrix/whatsapp/blob/main/build.sh very clearly says go build

> I tried to update with a git pull but was getting an error about using the master branch

do you want to try `main` branch? there is no `master` branch, so maybe you have something really old and cached.

**Comment by tulir** [comment]
That error only happens if you downgrade dependencies, it can't happen otherwise

One of the most common ways to downgrade is to switch from CI builds (which always have the latest dependencies) to compiling yourself (which will use outdated distro packages)
