### ISSUE TITLE
Broken communication between synapse (matrix) and bridge (mautrix)

### ISSUE THREAD

**Issue by carlitoxenlaweb** [mautrix/whatsapp#701]
Upgrading from 0.9.0 to 0.10.5+ will fail... Last working commit worked with compilation that can be used to upgrade the bridge itself: **f8a22aab063feaa8d641176b2bb4125c0024ffc2**

After that any other compilation will succeed but communication with server wont be stablished... If some old version is used then deprecated error will be throw and no login will be displayed

![imagen](https://github.com/mautrix/whatsapp/assets/8091126/864cd3e2-64ef-4e8e-b477-6c6c7f19ff87)

**Comment by tulir** [comment]
WhatsApp regularly blocks old client versions from connecting. Old bridge versions aren't supported in any case, only the latest version is supported.

**Comment by tulir** [comment]
Outdated synapse versions aren't supported either
