### ISSUE TITLE
problem with polls from WA

### ISSUE THREAD

**Issue by dxjirka** [mautrix/whatsapp#702]
Hi,
I have a problem with polls from WA.
Message looks like poll, but "inactive" (cannot be voted). When I check source code in Element client, there is "selectable_options_count": 0.

Polls from Matrix working fine in both, Matrix and WA.

mautrix-whatsapp v0.10.7

**Comment by tulir** [comment]
Works fine for me. Maybe you forgot to enable polls in the bridge config?
