### ISSUE TITLE
Document multi user access to a single WhatsApp account

### ISSUE THREAD

**Issue by h3ndrik** [mautrix/whatsapp#704]
I'd like to bridge two Matrix accounts to a single WhatsApp account. Both users should be able to receive and write messages. rooms should be created, backfilled and both users invited if someone opens a new chat on WA.

It's not really obvious how to do that and seems entirely undocumented. I'd like to have that included in the documentation.

It's not entirely clear how that's supposed to be set-up. I used to use relay mode, set in in the rooms and invite the other user. But that's a bit cumbersome and probably not the best solution. But it worked.

Now I just opened a conversation with @whatsappbot from the two accounts, sent `login` from both of them and scanned it with the same WhatsApp device. That opens a second connection that shows up in the WA app. Unfortunately no rooms were created for the second user. I managed to get the portals for group chats with the `sync` command, but direct messages from WA users are entirely missing on the second device.

I'm also not sure about the implications on doubble puppeting. I enabled that. Maybe that's causing issues? I also didn't grasp if I should `login-matrix` both users with the same appservice token or create two separate ones.

**Comment by tulir** [comment]
That's not supported
