### ISSUE TITLE
[FEAT] Do frequent login check

### ISSUE THREAD

**Issue by floviolleau** [mautrix/whatsapp#710]
Hi,

Thanks for maintaining this wonderful project. It is very helpful!

I have a small request/question.

I want to be notified when I'm logout from WhatsApp.

From time to time, I manually do a `!wa ping` in the bridge room but I would like to automate it 

Can you explain to me how to do that?

Thanks 🙏

**Comment by tulir** [comment]
The bridge already sends a notice to your management room if you get logged out

**Comment by floviolleau** [comment]
Hi,

How to configure it because this is not the case for me.

Thnaks for your help

**Comment by floviolleau** [comment]
Hi,

Please @tulir if you can guide me to know how to have notification when it is disconnected.

I'm using latest what's app bridge & synapse server.

Thank's a lot.
