### ISSUE TITLE
bridging different media types

### ISSUE THREAD

**Issue by kempertom** [mautrix/whatsapp#712]
I am not a developer but I am using mautrix on a frei.chat server mostly with SchildiChat or Element. Sending voice notes is no problem because the apps compresse these in a mautrix friendly way.
I would love to use FluffyChat. It is also possible to send voice notes to matrix users, but the WhatsApp bridge says: Your message was not bridged: unsupported media type "video/mp4" in audio message.
Is it possible to let mautrix bridge such files?
I am using SailfishOS. The native app (Sailtrix) has the same message, but without naming the media type.

**Comment by tulir** [comment]
Voice messages in Matrix must be ogg/opus
