### ISSUE TITLE
Let the user know if the bridge receives "client outdated" message 

### ISSUE THREAD

**Issue by JAicewizard** [mautrix/whatsapp#714]
The bridge suddenly stopped working yesterday, with no real reason, `reconnect` didn't result in any errors.
However looking at the logs, it became clear that the "client" is too old. It would be nice if this was made aware to the user when attempting to reconnect. (or even, in general when trying to connect and a failure happens)

**Comment by tulir** [comment]
The bridge doesn't receive client outdated messages anymore, but future versions will have a more unified error reporting system anyway
