### ISSUE TITLE
Bridged chat user avatar and nickname not up to date

### ISSUE THREAD

**Issue by ollietheotter983** [mautrix/whatsapp#715]
When in a bridged conversation, and this seems to go for any bridge, not just WhatsApp, but I wanna find out how to get it to work

When you update your name or avatar in Matrix, it works fine in non-bridged chats, but not in bridged ones. I dont know how but sometimes I have managed to get it to work.

Examples -
Non-bridged
![Screenshot_20240827_171442_Commet](https://github.com/user-attachments/assets/f44d9ce1-0a7c-495c-ba47-b3a4d960436a)
Bridged
![Screenshot_20240827_171455_Commet](https://github.com/user-attachments/assets/779c216a-52cb-4c85-91fa-382d374950fc)

**Comment by tulir** [comment]
Bridges don't affect your Matrix user's profile

**Comment by ollietheotter983** [comment]
It not the profile, it only happens in bridged chats
