### ISSUE TITLE
Rooms with bridge-to-end encryption are warned as unencrypted in Element

### ISSUE THREAD

**Issue by raphaelbadawi** [mautrix/whatsapp#718]
The issue is quite simple. When I enable bridge-to-end encryption, I actually can test it is working by connecting to a new device and not being able to see older messages in the room.

But Element seems to be unaware of this and still shows a warning at the top of the room stating that end to end encryption is not activated. So the room inconsistently looks like this:

![image](https://github.com/user-attachments/assets/3006ef74-b12e-41ef-90ec-2992d912fbd4)

It would be very nice to have those rooms flagged as encrypted by Element. But I'm not sure if the issue is on the bridge side or on the front side.

**Comment by tulir** [comment]
They are flagged as encrypted by Element unless there's something messing with the `m.room.encryption` event (which could be a bridge bug, but bugs in the old bridge won't be fixed as it's about to be rewritten)
