### ISSUE TITLE
Unsupported media type "video/quicktime"

### ISSUE THREAD

**Issue by kalidali256** [mautrix/whatsapp#726]
### Current behavior
When I send a quicktime (.mov) video via Element Matrix client to a Whatsapp contact via the bridge, the video message is not sent and the bridge bot logs the following error message:

`⚠ Your message was not bridged: unsupported media type "video/quicktime" in video message`

### Actual behavior
When I send a quicktime (.mov) video via Element Matrix client to a Whatsapp contact via the bridge, the video message should be sent to Whatsapp.

### Steps to reproduce
1. Create quicktime (.mov) video (default video format on IPhone)
2. Send it to a Whatsapp contact via Element Matrix client
3. Error message is visible in chat

### Notes
MP4 video do get bridged.

This issue is really annoying for all Apple users as quicktime (.mov) is the default video format when you record something.

**Comment by tulir** [comment]
You shouldn't send quicktime videos, most Matrix clients won't be able to render them either. The sending client can convert media to sensible formats when using platforms that default to non-sensible formats.

**Comment by kalidali256** [comment]
> You shouldn't send quicktime videos, most Matrix clients won't be able to render them either. The sending client can convert media to sensible formats when using platforms that default to non-sensible formats.

I just don't understand why Element or Synapse can handle and convert Quicktime to MP4 in "native" chats between users on the server. For example, I record a video on IPhone (Quicktime) and send to another user on the Synapse server. Then somewhere it gets converted to MP4 because the recipient can watch it on their Android Phone and the download of the video is also a MP4.

But it's not working with the bridged WA users?

**Comment by kalidali256** [comment]
> You shouldn't send quicktime videos, most Matrix clients won't be able to render them either. The sending client can convert media to sensible formats when using platforms that default to non-sensible formats.

Then why can the signal bridge handle quicktime videos with no problems?

**Comment by tulir** [comment]
The Signal bridge doesn't filter supported types, so it probably just sends videos that can't be viewed on signal android/desktop
