### ISSUE TITLE
relay mode, also respect the message_formats for the owner

### ISSUE THREAD

**Issue by celevra** [mautrix/whatsapp#736]
Hi,

if relay mode is activated the message_format is applied to all users that are using the relay.
But the user that is "owning" the relay sends the messages normal without, for example: "<b>celevra</b>: Message"

would be great if there is a setting that the message_format is also applied for the login owner if in relay mode in this room.

regards

**Comment by tulir** [comment]
Just use a different account for the relay bot

**Comment by celevra** [comment]
but than it is not possible to send messages without a prefix if nobody else is in a room
