### ISSUE TITLE
Bridge Update broke room names

### ISSUE THREAD

**Issue by ClemensElflein** [mautrix/whatsapp#753]
The last update broke all room names. The names were previously correct (i.e. `Contact Name (WA)`) but now all portals have changed the room name to the international phone number like `+49123456789 (WA)`.

I read in `v0.11.2` release notes that naming was addressed, but updating did not fix the names. The bot also does not have the `sync` command anymore.

Is this already known? If so, how can I fix / reimport the room names?

**Comment by ClemensElflein** [comment]
For anyone interested: relogin does the trick

**Comment by b1ggi** [comment]
a new user logged in, and then the portals from his WA Account were changed to telephone number only for all of us on the server. 

how would i force a recreation/renaming of the portal rooms ?

**Comment by b1ggi** [comment]
a new user logged in, and then the portals from his WA Account were changed to telephone number only for all of us on the server.

how would i force a recreation/renaming of the portal rooms ?

**Comment by z3ky** [comment]
> EDIT: like in [#732](https://github.com/mautrix/whatsapp/issues/732) my displayname was using .JID and not .Phone
> 
> a new user logged in, and then the portals from his WA Account were changed to telephone number only for all of us on the server.
> 
> how would i force a recreation/renaming of the portal rooms ?
> 
> User logged in while on v.0.11.0 , i updated to v.0.11.2 and did a re-login for my WA account, it didnt help

i also have this problem. logout login does not help. most contacts show the phone number. only a few show the name

**Comment by b1ggi** [comment]
Delete-all rooms did help, the logout login.

**Comment by z3ky** [comment]
A've already did and also setup a new home server. Still some contacts show the number, others the name.
I use `displayname_template: "{% raw %}{{or .PushName .FullName .JID}} (WA){% endraw %}"`

**Comment by z3ky** [comment]
revoking whatsapp app‘s access rights to the phone book and granting them again solved the problem. element shows all the names again

**Comment by ClemensElflein** [comment]
For me it works now with Android phones but does not with iPhones

**Comment by z3ky** [comment]
> For me it works now with Android phones but does not with iPhones

revoking access rights… works for me on ios
