### ISSUE TITLE
matrix -> whatsapp relies do not show replied-to message in whatsapp

### ISSUE THREAD

**Issue by JadedBlueEyes** [mautrix/whatsapp#754]
When replying to a message from Matrix, the Whatsapp message doesn't contain the replied-to message, only a link to it. See:
![image](https://github.com/user-attachments/assets/589ee006-328c-4554-8a37-4dcddf47f2d7)
This is different from the behavior of official whatsapp clients

**Comment by tulir** [comment]
Duplicate of #624
