### ISSUE TITLE
mautrix-whatsapp is attempting to bridge messages from unregistered users

### ISSUE THREAD

**Issue by OliveiraHermogenes** [mautrix/whatsapp#759]
I often invite to my portals a bot that automatically sends transcriptions of voice messages. Before upgrading to version v0.11.x, this worked as **I** expected: whatsappbot would just ignore those transcriptions if the portal was not set to relay messages from other matrix users to whatsapp.

Since upgrading to v0.11.2, whatsappbot is constantly warning the transcription bot that its messages were not bridged because it's not logged in. Is this intended behavior? Or should I double-check my configurations? If intended behavior, would it be out of the question to request a configuration option to revert back to the old behavior? (as I understand it, the old behavior was to only warn logged in users)

P.S.: I wondered whether the issue was happening because the transcriptions were being sent as replies to the original message from the whatsapp puppet (which would make the warnings more understandable from my perspective). However, tests with simple (non-reply) messages from the transcription bot yielded the same result.

Architecture: arm64
Homeserver: synapse 1.121.0
Mautrix-whatsapp v0.11.2
`message_error_notices` is set to `true` (I still want these warnings is the user is logged in)

**Comment by tulir** [comment]
That's intended. If you set the bot's permission to `block` in the bridge config, it should drop messages silently
