### ISSUE TITLE
login-matrix only works on homeserver from config

### ISSUE THREAD

**Issue by L1nk27** [mautrix/whatsapp#83]
Hi.
Today i tried to link my Matrix Account with the bridge with the "login-matrix" command.

My current setup is:
- Server A: Homeserver with the mautrix-whatsapp at my Home.
- Server B: Homeserver on a rented VPS.

My main account is on Server B and i write to the portals that lay on Server A.

When i try to link my account with the bridge, the bridge tries to run "whoami" on Server A and gets a 401 error.

Is there a option to change the request url so the bridge try to request on Server B instead of  Server A?

**Comment by tulir** [comment]
This is a known and somewhat intentional limitation. If you want to change it manually, change the first parameter in https://github.com/tulir/mautrix-whatsapp/blob/master/custompuppet.go#L65

**Comment by Yajo** [comment]
Why intentional?
